---
- hosts: all
  become: yes
  roles:
    - common

- hosts: db
  become: yes
  roles:
    - geerlingguy.mysql

- hosts: web
  become: yes
  roles:
    - nginx
    - jdk
    - tomcat-camunda
    # - japanization
