INSERT INTO companies (created_at, created_by, description, status_id, updated_at, updated_by, name, id)
VALUES (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'SFDC', 'company001'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'PwCコンサルティング', 'company002'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'PwCアドバイザリー', 'company003'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'あらた', 'company004'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'アクセンチュア', 'company005'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'デロイトトーマツコンサルティング', 'company006'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'トーマツ監査法人', 'company007'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'トーマツベンチャーサポート', 'company008'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'KPMGコンサルティング', 'company009'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'KPMG FAS', 'company010'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'IGPI', 'company011'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ABeam', 'company012'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Cap Gemini', 'company013'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'MURC', 'company014'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ベイカレント', 'company015'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'PCJ', 'company016'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'PTJ', 'company017'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Life Style Design', 'company018'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'From Scratch', 'company019'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Nagisa', 'company020'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Wondershake', 'company021'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Oneteam', 'company022'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Locus', 'company023'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Peach', 'company024'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'みらいワークス', 'company025'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Transferwise', 'company026'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'みらいワークスからの紹介企業', 'company027'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ファンド投資先（アパレル）', 'company028'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'アパレル', 'company029'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'SONY', 'company030'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '日立', 'company031'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'TBC', 'company032'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'インターワークス', 'company033'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Intloop', 'company034'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'スカイライト', 'company035'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ベルテクスパートナーズ', 'company036'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ガートナー', 'company037'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Protiviti', 'company038'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'シグマクシス', 'company039'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'シンプレクス', 'company040'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'SJNK', 'company041'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'AIG', 'company042'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'MSAD', 'company043'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'WingArc1st', 'company044'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'アリックスパートナーズ', 'company045'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'BBS', 'company046'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Avanade', 'company047'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'beBit', 'company048'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Amaxon', 'company049'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'IBM', 'company050'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ソニー生命', 'company051'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '日産', 'company052'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '日産Tech', 'company053'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'アクサ', 'company054'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'アクサTech', 'company055'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'メットライフ', 'company056'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'NN生命', 'company057'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Rational Works', 'company058'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '中国向けポジション：チャイナトップ', 'company059'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'BC Holidings 田中学習会 (CLSA Portfolio)', 'company060'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Oh My Glasses Tokyo（NCC系）', 'company061'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Coconala（NCC系）', 'company062'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'チームスピリット (NCC系）', 'company063'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '47 (NCC系）', 'company064'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'CYDAS (NCC系）', 'company065'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '住友不動産', 'company066'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'bankguard', 'company067'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'boku', 'company068'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ceres', 'company069'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'crowd cast', 'company070'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'crowd credit', 'company071'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'エイト証券', 'company072'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'paidy', 'company073'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'freee', 'company074'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'GA technologies', 'company075'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'heroz', 'company076'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'infcurion', 'company077'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'jintec', 'company078'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'JPLinks', 'company079'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'kanmu', 'company080'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'kyash', 'company081'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Liquid', 'company082'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'makeleaps', 'company083'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'merrybiz', 'company084'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'MFS', 'company085'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'お金のデザイン', 'company086'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'money tree', 'company087'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Omise', 'company088'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'one tap buy', 'company089'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'opro', 'company090'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'orb', 'company091'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'quoine', 'company092'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'R＆AC', 'company093'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'Realworld', 'company094'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'ResuPress(coincheckを展開)', 'company095'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'payoneer', 'company096'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'チームスピリット', 'company097'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'tradeshift', 'company098'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'transferwise', 'company099'),
  (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', 'バリューデザイン', 'company100'), (SYSDATE(), 'user1', NULL, 'status15', SYSDATE(), 'user1', '財産net', 'company101');
