INSERT INTO `categories` (`id`, `created_at`, `created_by`, `description`, `status_id`, `updated_at`, `updated_by`, `domain`, `name`)
VALUES ('category00', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'なし'),
  ('category01', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'IT'),
  ('category02', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'コンサルティング'),
  ('category03', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'アパレル'),
  ('category04', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'エアライン'),
  ('category05', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '人材'),
  ('category06', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '製造'),
  ('category07', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '電機'),
  ('category08', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '金融'),
  ('category09', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '小売'),
  ('category10', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'メーカー'),
  ('category11', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '教育'),
  ('category12', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'Webサービス'),
  ('category13', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'クラウドソフトウェア'),
  ('category14', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'オフィスソリューション'),
  ('category15', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '不動産'),
  ('category16', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '決済インフラ'),
  ('category17', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '広告インフラ'),
  ('category18', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'スタートアップ支援'),
  ('category19', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '投資インフラ（クラウド）'),
  ('category20', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '会計ソフト'),
  ('category21', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '物件検索アプリ'),
  ('category22', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'AI×mobile'),
  ('category23', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '決済・金融コンサル'),
  ('category24', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '顧客データベースマネジメント'),
  ('category25', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '送金のプラットフォーム開発'),
  ('category26', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '決済カード関連'),
  ('category27', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '通貨インフラ'),
  ('category28', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '本人認証インフラ'),
  ('category29', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'クラウド型請求ソフト'),
  ('category30', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '経理入力アウトソーシング'),
  ('category31', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '住宅ローン関連'),
  ('category32', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '金融サービス'),
  ('category33', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '家計簿アプリサービス'),
  ('category34', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '決済インフラ事業'),
  ('category35', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'スマホ証券'),
  ('category36', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'クラウドインフラ'),
  ('category37', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '地方創生クラウド開発'),
  ('category38', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '仮想通貨ベンチャー'),
  ('category39', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '業務改善システムインフラ'),
  ('category40', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'ビットコインサービス'),
  ('category41', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '決済プラットフォーム事業'),
  ('category42', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '業務改善サービス'),
  ('category43', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'ITソリューション'),
  ('category44', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', '海外送金サービス'),
  ('category45', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'バリューカードASPサービス'),
  ('category46', SYSDATE(), 'user1', NULL, NULL, SYSDATE(), 'user1', 'Company', 'ニュース・財産管理事業');

INSERT INTO companies_categories (company_id, category_id)
VALUES ('company001', 'category01'), ('company002', 'category02'), ('company003', 'category02'), ('company004', 'category02'), ('company005', 'category02'),
  ('company006', 'category02'), ('company007', 'category02'), ('company008', 'category02'), ('company009', 'category02'), ('company010', 'category02'),
  ('company011', 'category02'), ('company012', 'category02'), ('company013', 'category02'), ('company014', 'category02'), ('company015', 'category02'),
  ('company016', 'category02'), ('company017', 'category01'), ('company018', 'category03'), ('company019', 'category01'), ('company020', 'category01'),
  ('company021', 'category01'), ('company022', 'category01'), ('company023', 'category01'), ('company024', 'category04'), ('company025', 'category05'),
  ('company026', 'category01'), ('company027', 'category06'), ('company028', 'category03'), ('company029', 'category03'), ('company030', 'category07'),
  ('company031', 'category07'), ('company032', 'category02'), ('company033', 'category01'), ('company034', 'category02'), ('company035', 'category02'),
  ('company036', 'category02'), ('company037', 'category02'), ('company038', 'category02'), ('company039', 'category02'), ('company040', 'category02'),
  ('company041', 'category08'), ('company042', 'category08'), ('company043', 'category08'), ('company044', 'category01'), ('company045', 'category02'),
  ('company046', 'category02'), ('company047', 'category02'), ('company048', 'category02'), ('company049', 'category09'), ('company050', 'category01'),
  ('company051', 'category08'), ('company052', 'category06'), ('company053', 'category01'), ('company054', 'category08'), ('company055', 'category08'),
  ('company056', 'category01'), ('company057', 'category08'), ('company058', 'category01'), ('company059', 'category10'), ('company060', 'category11'),
  ('company061', 'category10'), ('company062', 'category12'), ('company063', 'category13'), ('company064', 'category14'), ('company065', 'category13'),
  ('company066', 'category15'), ('company067', 'category16'), ('company068', 'category16'), ('company069', 'category17'), ('company070', 'category18'),
  ('company071', 'category19'), ('company072', 'category00'), ('company073', 'category16'), ('company074', 'category20'), ('company075', 'category21'),
  ('company076', 'category22'), ('company077', 'category23'), ('company078', 'category24'), ('company079', 'category25'), ('company080', 'category26'),
  ('company081', 'category27'), ('company082', 'category28'), ('company083', 'category29'), ('company084', 'category30'), ('company085', 'category31'),
  ('company086', 'category32'), ('company087', 'category33'), ('company088', 'category34'), ('company089', 'category35'), ('company090', 'category36'),
  ('company091', 'category37'), ('company092', 'category38'), ('company093', 'category39'), ('company094', 'category36'), ('company095', 'category40'),
  ('company096', 'category41'), ('company097', 'category42'), ('company098', 'category43'), ('company099', 'category44'), ('company100', 'category45'),
  ('company101', 'category46');
