INSERT INTO applicants (id, created_by, updated_by, created_at, updated_at, description, age, birth_day, name, status_id) VALUES
  ('applicant001', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '1．アクセンチュア（金融事業本部）\n 2．AIU', null, '1992-10-18', '稲田 克明', 'status03'),
  ('applicant002', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1980-09-09', '河野 由文', 'status02'),
  ('applicant003', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1979-04-29', '米田 たか子', 'status03'),
  ('applicant004', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1980-02-04', '日高 倉美', 'status03'),
  ('applicant005', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1984-06-01', '金田 忠之', 'status03'),
  ('applicant006', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1984-09-09', '横山 輝志郎', 'status02'),
  ('applicant007', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1975-11-25', '松原 れいな', 'status02'),
  ('applicant008', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1986-10-09', '川島 清一', 'status03'),
  ('applicant009', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1982-07-18', '山根 信広', 'status03'),
  ('applicant010', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井住友銀行出身', null, '1983-09-26', '津田 道和', 'status03'),
  ('applicant011', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '外資（3M）BDヘッド\n ⇒コニカミノルタBDヘッド', null, '1990-10-24', '後藤 仁美', 'status03'),
  ('applicant012', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '制作会社⇒読売広告社⇒国際フォーラム', null, '1992-03-27', '倉田 理香', 'status03'),
  ('applicant013', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '国税', null, '1990-12-19', '山崎 光善', 'status03'),
  ('applicant014', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'メーカー＠中国\n ⇒一橋MBA', null, '1982-08-03', '児玉 安彦', 'status02'),
  ('applicant015', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1972-09-26', '大平 知子', 'status03'),
  ('applicant016', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱UFJモルガンスタンレー証券\n ⇒MBA留学＠ロス', null, '1986-07-10', '花田 義子', 'status03'),
  ('applicant017', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, '1984-05-26', '小山 伸江', 'status03'),
  ('applicant018', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '臼井 寿彦', 'status03'),
  ('applicant019', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '大野 秋代', 'status03'),
  ('applicant020', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'エッソ⇒日本通運⇒日本アムウェイ⇒米国系投資ファンドTPGの依頼により、エイボン・プロダクツ株式会社BPRプロジェクトマネジャー（生産外注化および工場閉鎖担当）', null, null, '田島 知生', 'status03'),
  ('applicant021', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '木下 虎之助', 'status03'),
  ('applicant022', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '荒井 恵治', 'status03'),
  ('applicant023', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日立建機、外務省出向、シーメンス', null, null, '徳田 泰央', 'status03'),
  ('applicant024', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東芝ソリューションズ（PMP、ブラックベルト）', 55, null, '小松 世弥', 'status03'),
  ('applicant025', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SMBC、メタルワン、INCJ参加企業CFOアプライ検討中\n （品川駅スタバにて面談）', null, null, '稲田 咲子', 'status03'),
  ('applicant026', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '河合 俊憲', 'status03'),
  ('applicant027', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トチキン⇒IT Design（スケジュール同期ソリューション/Googleクラウド活用型オリンピック向けソリューション）', null, null, '小柳 敬志', 'status03'),
  ('applicant028', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'IBM', null, null, '藤井 安彦', 'status03'),
  ('applicant029', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士通US COO', null, null, '関口 明博', 'status03'),
  ('applicant030', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本GE', null, null, '上野 一城', 'status03'),
  ('applicant031', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ信託⇒キーポート・ソリューションズ⇒ライフタイム パートナーズ⇒社団法人全国社会保険協会連合会', null, null, '長谷川 信也', 'status03'),
  ('applicant032', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '長銀⇒トラコス⇒独立コンサル（再生/事業戦略）⇒がってん寿司', null, null, '武藤 訓', 'status03'),
  ('applicant033', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'IBM（パートナーで退職）', null, null, '村瀬 三光', 'status03'),
  ('applicant034', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NTT国際事業部（国際系コンサルのチームアップ）⇒ソフトバンク海外事業戦略', null, null, '畠山 秋徳', 'status03'),
  ('applicant035', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '山崎 繁樹', 'status03'),
  ('applicant036', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ディズニー⇒セガ⇒・・・⇒Duchbill', null, null, '津田 茂俊', 'status02'),
  ('applicant037', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '村田 多恵子', 'status03'),
  ('applicant038', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '公認会計士', null, null, '黒沢 健之', 'status03'),
  ('applicant039', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'デロイトHCメンバー', null, null, '荒木 幹也', 'status03'),
  ('applicant040', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN HCMメンバー', null, null, '齋藤 信広', 'status03'),
  ('applicant041', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN HCMメンバー', null, null, '柳田 要子', 'status03'),
  ('applicant042', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ニッセイ、保険金支払⇒商品企画⇒コンプライアンス', null, null, '高瀬 織枝', 'status02'),
  ('applicant043', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SEの方', null, null, '牧野 由記彦', 'status03'),
  ('applicant044', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '広告代理店（横浜アーチスト）勤務の方', null, null, '内海 れいや', 'status03'),
  ('applicant045', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'CTCテクノロジー', null, null, '飯島 慶太郎', 'status03'),
  ('applicant046', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '吉原 義郎', 'status02'),
  ('applicant047', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井不動産の中国/アジアマーケティング担当（リサーチ等を担当）', null, null, '山根 寿美', 'status02'),
  ('applicant048', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '田島 奈緒', 'status03'),
  ('applicant049', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '長野 晶紀', 'status03'),
  ('applicant050', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'TOEIC990点、日本大学卒、株式会社MCJ経営企画', 41, null, '片岡 吉治', 'status03'),
  ('applicant051', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'TOEIC835点、IRジャパン（PR会社）、リサーチャー、グローバル経験あり', 27, null, '杉山 良市', 'status03'),
  ('applicant052', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '成蹊大学卒、フィリップス、マーケティング/販促企画', 29, null, '小山 季孝', 'status03'),
  ('applicant053', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '九州大谷短期大学卒、株式会社コスモ、経営企画/テクニカルサポート/サーバーネットワークエンジニア、現450万円', 34, null, '岡野 ハルノ', 'status03'),
  ('applicant054', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本大学卒、インフォレスト株式会社、経営企画、現800万円', 43, null, '岡野 昭二', 'status03'),
  ('applicant055', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社グッドスパイラル、フードレストランの店舗管理/海外展開推進（シンガポール）/財務経理/IR、現500万円、TOEIC630点', 37, null, '金子 錦也', 'status03'),
  ('applicant056', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '中央大学卒、IBM', 30, null, '上田 周平', 'status02'),
  ('applicant057', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社五十嵐惣一工務店（経営企画）', 45, null, '片岡 令', 'status03'),
  ('applicant058', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '阪大卒、株式会社YAZ（プロジェクトマネジャー）', 35, null, '三上 君吉', 'status03'),
  ('applicant059', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'リクルート住まいカンパニー（北海道）', 28, null, '菅 公生', 'status01'),
  ('applicant060', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、JAL、守谷市議会議員事務所', 40, null, '中山 郁美', 'status03'),
  ('applicant061', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'テクタイト株式会社、サイバーステップ株式会社、株式会社近畿システムサービス（派遣）、NTTSingapore Pte Ltd', 33, null, '原 美次', 'status03'),
  ('applicant062', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '青山学院大学卒、株式会社プレシステムクリエイト、株式会社日本エル・シー・エー、ビジネスキューブ・アンド・パートナーズ株式会社、Lunascape株式会社、シルバーエッグ・テクノロジー株式会社、ReachLocal Japan Services合同会社', 38, null, '西本 智治', 'status03'),
  ('applicant063', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '早稲田卒、株式会社エヌ・ティ・ティ エムイー、沖電気工業株式会社、日本オラクル株式会社、アイホン株式会社', 39, null, '植田 一典', 'status03'),
  ('applicant064', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東洋大卒、株式会社初穂、日産（クレジット事業）、丸井（旅行事業）、ホテルグリーンプラザ、株式会社デルフィス（トヨタ自動車100%出資：マーケティング）、株式会社サイバーウィング（NEC日本電気連結グループ会社）、株式会社ブロードバンドタワー、株式会社フレスコエンジニアリング、株式会社ラスターワークス、株式会社サイバーウィング（NECビッグローブ連結会社）', 49, null, '田島 美智', 'status03'),
  ('applicant065', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京マルチメディア卒、戦術飛行団、株式会社千湖テクス（チェンホテクス）、株式会社エオロジャパン、ペンタイン株式会社（SIer）', 42, null, '天野 茂平', 'status03'),
  ('applicant066', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、大和証券、マクニカ（日本勤務/シンガポール駐在)、HOYA Electronics Singapore Pte. Ltd,.', 45, null, '丸山 知生', 'status03'),
  ('applicant067', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京会計専門学校卒、株式会社サイビーンズ（直近）', 39, null, '篠田 嘉彦', 'status03'),
  ('applicant068', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SAPジャパン、Arrows Consulting、個人事業主（SAPプロジェクト）', 55, null, '園田 省次郎', 'status03'),
  ('applicant069', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '大蔵省、東京税関、ソフトバンク、NTTコミュニケーションズ、株式会社アンラボ', 46, null, '富田 雄一郎', 'status03'),
  ('applicant070', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NEC、NECアメリカ、アークス、丸ヨ池内、医療法人社団慶友会\n （経企/財務を長く経験）', 44, null, '梅田 拓夫', 'status03'),
  ('applicant071', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア', 38, null, '野口 栄理子', 'status02'),
  ('applicant072', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ウィルコム、ソフトバンク営業', 29, null, '斉藤 希美', 'status03'),
  ('applicant073', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士通、ソニーグローバルソリューションズ', 49, null, '畠山 利浩', 'status03'),
  ('applicant074', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'イトーキ、ユニリーバ、トヨタユーゼック', 53, null, '溝口 忠和', 'status03'),
  ('applicant075', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'エルシーエー、ジェイック、TREASURE HUNTING、AIU、コーポレートアドバイザーズと経営コンサルティングを複数経験', 51, null, '三谷 希', 'status03'),
  ('applicant076', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東芝ソリューションズ', 39, null, '宮原 ひびき', 'status03'),
  ('applicant077', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'CSIソリューションズ、バッファロー', 36, null, '飯島 省次郎', 'status03'),
  ('applicant078', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニー（国内/APAC）', 56, null, '橋本 亮子', 'status03'),
  ('applicant079', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア、事業を協同で操業、KPMG', 35, null, '片岡 好利', 'status03'),
  ('applicant080', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Colorado Mountain College卒、カメイ、インターナショナル・コネクションズLLC', 39, null, '須藤 厚史', 'status03'),
  ('applicant081', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'オリックス、QUICK、PwC', 48, null, '田口 玲一', 'status03'),
  ('applicant082', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '北京軟通動力技術有限会社、IBM（Chine/Japan）、積水化学', 44, null, '早川 郁美', 'status02'),
  ('applicant083', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'インターゲイト、学校法人中央大学 理工学部 情報工学科\n 教育技術員、アイネットワークスジャパン、三十三、サクシード\n （ICT業界での数多くのプロジェクト実績あり）', 40, null, '成田 久江', 'status03'),
  ('applicant084', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '八文字会計事務所、住商テキスタイル、スミテックス・インターナショナル\n （国内外での財務/経理を幅広く経験）', 42, null, '小島 愛作', 'status03'),
  ('applicant085', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '脇坂英数塾、JICA、外務省/OECD(経済協力開発機構）日本政府代表部一等書記官\n （パリ在住）', 42, null, '古谷 三保子', 'status03'),
  ('applicant086', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'IVTL Infoview Technologies Pvt., Ltd.\n （Operation/Sales/Delivery全てを幅広く経験）', 35, null, '笠原 有三', 'status01'),
  ('applicant087', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 32, null, '飯島 芙美子', 'status03'),
  ('applicant088', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SAP、デロイト、クリード、オールアバウト、ユニバース、EY\n （KPMGの最終面談予定）', 37, null, '大橋 八洲子', 'status03'),
  ('applicant089', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 41, null, '栗原 泳助', 'status03'),
  ('applicant090', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'エス・ライン、三光ソフラン、ソフトバンクBB、コールトゥウェブ、光通信', 38, null, '川野 章緒', 'status03'),
  ('applicant091', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京セラ、トヨタテクニカルディベロップメント\n （生産管理、R&D、品質管理、PM）', 38, null, '柏木 洵子', 'status03'),
  ('applicant092', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日揮、NRI、コンサルファーム', 56, null, '大沢 祐子', 'status03'),
  ('applicant093', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '(株)弘報社、札幌通運株式会社', 36, null, '浜崎 圭織', 'status03'),
  ('applicant094', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'りそな、アイディーユー、GateKeeperCorporation、デューデリ＆ディール\n （金融/不動産/M&Aの経験）', 40, null, '大山 凱次', 'status03'),
  ('applicant095', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '4社のSIerを経験\n （EBS/SAPなど多数経験）', 38, null, '上田 常次', 'status01'),
  ('applicant096', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本旅行、ジョンソン・エンド・ジョンソン、ソニー生命、ライフタイムパートナーズ（医療コンサル）、アポプラスステーション、ハートホスピタルパートナーズオブジャパン', 39, null, '藤村 芙美', 'status03'),
  ('applicant097', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'メガバンク（証券）、大手監査法人系コンサル、海外渡航関連サービス企業、経営コンサル', 45, null, '市川 征四郎', 'status03'),
  ('applicant098', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京大卒、野村コンピュータシステム、野村綜合研究所香港有限公司、SAPジャパン、エックスエヌ（起業）\n 東南アジアを中心にODAを活用したIT関連プロジェクト多数経験あり\n TOEIC880', 55, null, '上村 厚史', 'status03'),
  ('applicant099', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'エフ・ディ・シィプロダクツ、エックスネット（金融機関向けITコンサル）', 34, null, '吉野 松次郎', 'status01'),
  ('applicant100', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '山陽新聞、光通信、西日本法規出版、友野印刷、マリンポス', 42, null, '大田 泰秀', 'status03'),
  ('applicant101', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士銀行、スタンダードチャータード銀行、HSBC、あおぞら銀行', 48, null, '吉村 江美', 'status03'),
  ('applicant102', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '積水化学、INAひまわり、三井デザインテック、トヨタホーム、三井デザインテック', 43, null, '原 志奈', 'status03'),
  ('applicant103', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日立電線、日立製作所、ウィザス\n （税理士 / 日商簿記検定1級 / MBA / 中小企業診断士 / ファイナンシャル・プランナー（AFP/CFP））', 45, null, '平山 有子', 'status03'),
  ('applicant104', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱重工（技術）、テクノコンサルタンツ（技術コンサル）、イーアンドイーソリューションズ（環境コンサル）', 52, null, '神田 武久', 'status03'),
  ('applicant105', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東大卒、東大理学部研究所、三菱電機CEO、東京ディズニーリゾートCEO、シャネル、ルイヴィトンCEO、NTTコミュニケーションズCEO\n 年収5,000万円', 44, null, '石原 千恵', 'status03'),
  ('applicant106', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社フォーバルCEO(SI/IT機器/クラウドサービス）', 46, null, '中西 悠里', 'status03'),
  ('applicant107', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'コミッションダイバー', null, null, '中尾 恭造', 'status03'),
  ('applicant108', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアM3、Mizuho Sec（出向中で過去に転職を検討したことあり）\n コンテンツ系/ソリューション系、今回Promあり\n Yさん退職は伝えない', null, null, '大城 貴浩', 'status01'),
  ('applicant109', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM3、三菱のIT子会社出身\n コンテンツ系、SMBC Nikko\n Yさんの退職伝え済み', null, null, '樋口 勝人', 'status01'),
  ('applicant110', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM3、Aeon Bank\n マルチタイプ（PMO）、インダストリーのこだわりなし\n 12月末までPJ延長、その先は改めて検討（但し拡大を指示されるもスタッフを付けてもらえない状況）\n Yさんの退職伝え済み', null, null, '原 文典', 'status03'),
  ('applicant111', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア', null, null, '石崎 文吾', 'status03'),
  ('applicant112', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '白川 多恵子', 'status03'),
  ('applicant113', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM2、元T&OP、Mizuho Sec\n マルチタイプ（PMO）、インダストリーのこだわりなし、現在神さん配下\n FSA対応等実施、向こう1年くらいは転職しない可能性\n Yさんの名前は出さない', null, null, '中川 寿彦', 'status03'),
  ('applicant114', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM2、Nomura Sec\n 御用聞き系（PMO)、グローバル系、3年前にCHTからトランスファー\n Yさんの名前出すのはOK', null, null, '矢野 光次', 'status01'),
  ('applicant115', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM1、SMBC Nikko\n ACに対するロイヤリティはあり、中野さんとの結びつきもあり（但しそこまで強くなさそう）\n Yさんの名前は出さない', null, null, '三木 信春', 'status01'),
  ('applicant116', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアSM1、MUTB\n 中途入社、コンテンツ系/ソリューション寄り、コンサルというよりは業務設計等のSE、今回Promあり\n Yさんの退職伝え済み', null, null, '和田 泰秀', 'status01'),
  ('applicant117', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアM4\n コンテンツ系、今回Promなし\n ACNでのキャリアも考えたい模様', null, null, '西川 芙美子', 'status01'),
  ('applicant118', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアM3、Mizuho Sec（出向中）\n ポテンシャルは非常に高い、ACNに見切りをつけようとしている模様、今回Promなし（元々期待していない）\n ベンチャー/新規事業に興味ありの可能性（給与というよりは）\n Yさんの退職伝え済み', null, null, '杉田 雅生', 'status02'),
  ('applicant119', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアM3、Mizuho Sec（6，7年間ずっと）\n 今回Promなし、神さんとの結びつきは強め\n Yさんの名前出すのはOK', null, null, '菊池 一典', 'status03'),
  ('applicant120', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '組込/カーナビエンジニア、ACN（9年目：CMT⇒FS、今M5）\n 大学時代にUKへ留学経験あり', 36, null, '菅野 督彦', 'status03'),
  ('applicant121', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '大和総研、ACN', 35, null, '茂木 優香', 'status03'),
  ('applicant122', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '齋藤 希', 'status01'),
  ('applicant123', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアM2\n 香港常駐（Japan Deskとして）、グローバルPMO系\n PwCとしてはJP採用/現地採用の双方が可能（By 足立さんヒアリング）', null, null, '田島 数也', 'status03'),
  ('applicant124', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュアC2、Mizuho Sec\n 野村から来て2，3年目', null, null, '小松 松代', 'status03'),
  ('applicant125', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'A3\n TOEIC850', 26, null, '小柳 三保子', 'status01'),
  ('applicant126', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 27, null, '新井 右京', 'status01'),
  ('applicant127', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 31, null, '竹内 研五', 'status03'),
  ('applicant128', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '営業戦略/新規ビジネス/マーケティング/経営管理を担当（社名は不明）\n MBA、HRプロフェッショナル（日本生産性本部）、JMAA認定M＆Aアドバイザー保有', 40, null, '松崎 栄理子', 'status01'),
  ('applicant129', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'パソナ、日本アウトソーシング、CREWS（ハワイ）、他\n 日商簿記2級', 41, null, '宮城 記代', 'status03'),
  ('applicant130', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アフラック、ジブラルタ、ダイレクトソリューションズ、他\n （現在はフリーランス）', 42, null, '本間 三保子', 'status01'),
  ('applicant131', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニーエイゴン、医療機器商社、他\n TOEIC930、中国語/スペイン語：初級', 42, null, '谷川 明久', 'status02'),
  ('applicant132', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソフトウェア興業、JICA\n 日商簿記2級、建築経理士、CPA（取得中）', 38, null, '杉原 軍市', 'status03'),
  ('applicant133', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '花王、ナインシグマジャパン\n TOEIC880', 34, null, '荒井 育雄', 'status01'),
  ('applicant134', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ヒューストン大卒、株式会社PALTEK、サンドバースト・コーポレーション、株式会社シンインドトレーディングアンドコンサルティング他\n 中小企業診断士', 36, null, '緒方 鋭充', 'status03'),
  ('applicant135', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '北海道大学、APEX VIETNAM、A.I GLOAL SUN PARTNERS、中央総合ビジネスコンサルティング\n TOEIC805、日商簿記2級、公認会計士受験中', 38, null, '丸山 由雄', 'status03'),
  ('applicant136', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱東京UFJ銀行、静岡信用金庫、株式会社スクロール\n 公認会計士、証券アナリスト', 41, null, '白石 洋昌', 'status03'),
  ('applicant137', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京都大学卒、IBM、ユニリーバ、デロイト、フィリップス、LIXILグループ\n TOEIC890', 31, null, '桑原 芳尚', 'status03'),
  ('applicant138', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '朝日監査法人、環境省、あずさ監査法人\n 会計士、税理士、TOEIC855', 43, null, '森本 初', 'status03'),
  ('applicant139', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ランカスターマネージメントスクール（英国）卒、クレジット債権管理組合、ピツニーボウズ・ジャパン株式会社、アイ・エム・エス・ジャパン株式会社、ノボノルディスクファーマ株式会社、Transcu Ltd.（シンガ）、ンド・インスティチュート・インク、独立コンサルタント\n TOEIC925、MBA、USCPA（取得中）', 43, null, '菅 葉子', 'status03'),
  ('applicant140', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '光美容化学、株式会社ケーブルテレビ山形等を経て、秋田フットボールクラブ株式会社プロスポーツマネージメントに従事', 42, null, '菅原 好利', 'status03'),
  ('applicant141', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日系自動車部品メーカ、スウェーデン系ERPシステム導入コンサルティング会社 、外資系自動車部品メーカ、アメリカ系不動産投資ファンド会社、アメリカ系小売業を対象とした万引防止システム販売会社等を経て、キャップジェミニ\n CPA（米国公認会計士） / 証券外務員二種 / 宅地建物取引主任者/IPO上級実務者', 40, null, '丹羽 悠子', 'status03'),
  ('applicant142', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京海上日動、Tokio Marine Asia・P&C Underwriting Dept・Manager（シンガポール・中間管理会社）\n シンガポール在住、TOEIC910', 32, null, '高島 松次郎', 'status03'),
  ('applicant143', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'フルライン株式会社、ネクステック株式会社（後の経営共創基盤）、株式会社エスプール総合研究所他、現在は株式会社HORIZON ARCHITECTのCEO', 41, null, '北村 益三', 'status01'),
  ('applicant144', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社富士通システムズ・イースト（旧：富士通システムソリューションズ）、監査法人トーマツ（医療系サービス展開チームか?）', 28, null, '河野 茂也', 'status03'),
  ('applicant145', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本能率協会、株式会社アクティブアンドカンパニー（組織/人事コンサル）', 30, null, '松下 悠里', 'status01'),
  ('applicant146', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '大和証券（VCや投資先CEO、海外勤務など歴任）、ネミーインベストメント株式会社CEO', 57, null, '土屋 克三', 'status03'),
  ('applicant147', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '地方銀行、外資系監査法人、Sler、メーカー\n ERP導入経験あり、国内外経理/財務のマネジメント経験あり、TOEIC920、銀行業務検定財務2級、USCPA（取得中）', 44, null, '馬場 菊子', 'status01'),
  ('applicant148', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '博報堂、株式会社ブロッサム（検索エンジンexciteの翻訳エンジンの企画/開発）、株式会社ハンドカッツレコード（“アヴゥリル・ラヴィーン”のジャパンツアー及びアパレルブランド\n “アヴィーダウン”を日本で展開）、株式会社ランドジャパン（クリスピークリームドーナツの日本展開、NYのアパレルブランド“オープニングセレモニー”を日本にローンチ）、SMAX株式会社（ハワイのパンケーキブランド“カフェ・カイラ”を日本にローンチ）、ヒップスター・インターナショナル株式会社（ハワイのパンケーキブランド“モエナカフェ”を日本にローンチ）\n TOEIC850', 43, null, '浜野 研五', 'status03'),
  ('applicant149', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京都大学卒、食品会社、上海某企業管理コンサル有限公司、銀行系調査・コンサルティング会社\n \n 中国語ネイティブに近い\n ファイナンシャル・プランナー（AFP/CFP）、日商簿記検定３級、財務・経理検定（ＦＡＳＳ検定）Ａレベル', 33, null, '瀬戸 望', 'status01'),
  ('applicant150', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '関西外語大学卒、三泰貿易株式会社（自動車の海外輸出/販売）、サカモト産業株式会社（建設機械の輸出入）、ＵＡプロダクション（建設機械の輸出入）にて経営企画/マーケティング/営業を担当\n TOEIC735', 37, null, '前田 歩', 'status03'),
  ('applicant151', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NTTデータ、アクセンチュア、キャップジェミニ、アビーム（恐らくPartner）\n TOEIC650\n 情報処理技術者 システムアナリスト及びアプリケーションエンジニア 資格保持、SAP認定コンサルタント FI/CO', 49, null, '二宮 悠子', 'status03'),
  ('applicant152', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニー、EY税理士法人（TPライン）\n TOEIC905\n 会計士/税理士', 51, null, '榊原 彰揮', 'status03'),
  ('applicant153', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'CITIBANK、矢矧コンサルタンツ、株式会社NTTデータ経営研究所、株式会社ベンチャー・リンク、アーサーアンダーセン他', 56, null, '奥山 栄之介', 'status03'),
  ('applicant154', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ボスコン、ボスコン（シンガ）、ベルガー、ロバート・ウォルターズ、HENKEL（ドイツ）\n TOEIC940\n MBA', 41, null, '川野 周平', 'status03'),
  ('applicant155', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '石油開発会社（経営企画部、財務部）\n TOEIC935\n 日商簿記2級', 29, null, '池上 由水', 'status03'),
  ('applicant156', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'キングス・カレッジ・ロンドン（ロンドン大学）、シンクタンクでのインターンを2つ経験', 26, null, '内田 文之', 'status03'),
  ('applicant157', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'カリフォルニア大学ロサンゼルス校卒、三菱UFJ信託銀行、株式会社ファミリー（塾講師）、ネイチャーインターナショナル株式会社（コンサルタント）', 30, null, '柳田 道義', 'status01'),
  ('applicant158', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社オルカカナダ、在バンクーバー日本総領事館（マーケティング/市場参入/APECサポート等）、在日カナダ商工会議所、株式会社ＤＤＮコンサルティング（ビジネスコンサル）、株式会社雪国まいたけ（新規事業）、株式会社アイビー化粧品（海外事業構想/推進、国内事業構想/マーケティング等）\n TOEIC830\n MBA', 45, null, '森岡 美哉', 'status03'),
  ('applicant159', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社中日カラー、株式会社ビジテム、株式会社富永電子システム、株式会社ブロードバンドタワー、エヌシーアイ株式会社（双日グループ）\n ネットワークやシステム管理の経験多数', 36, null, '長岡 眞美', 'status03'),
  ('applicant160', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'KDDI、ソフトバンクモバイルのマネジメントとの太いパイプあり', 56, null, '平野 るり子', 'status03'),
  ('applicant161', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 49, null, '竹下 優紀', 'status03'),
  ('applicant162', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '早稲田卒、BASF Catalyst (Shanghai) （インターン）、株式会社ABC（リサーチ/マーケティング）、29アイランズ合同会社（M&A海外事業部）\n ビジネス英語OK', 29, null, '高松 初美', 'status01'),
  ('applicant163', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京大卒、キヤノンマーケティングジャパン、アビーム\n TOEIC800\n  第一種情報処理技術者 / SAP認定資格 / マイクロソフト認定資格(MCA) / オラクル認定資格 / 日商簿記検定2級', 27, null, '村山 ひとみ', 'status03'),
  ('applicant164', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '明治学院大学卒、伊藤忠テクノソリューションズ\n TOEIC635：ビジネスレベル', 31, null, '辻 久哉', 'status01'),
  ('applicant165', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '横浜国立大学卒、機械加工メーカー、エンジニアコンサル、治験/臨床/医薬品メーカー\n 管理会計士 Part 2（財務情報分析、企業財務、グローバル経営、設備投資意思決定分析など）\n - BATIC, Controller Level, Score 991（米国基準&国際財務報告基準）\n - IFRSs learning and assessment program（国際財務報告基準検定）\n - 日商簿記1級', 38, null, '福島 喜男', 'status03'),
  ('applicant166', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トラベルジャーナルツーリズムホスピタリティー専門学校卒、Shangri La Tours Pvt.Ltd,、株式会社森ビル グランドハイアット六本木、楽天トラベル（海外企画統括）\n TOEIC895：ネイティブ', 38, null, '谷 源平', 'status03'),
  ('applicant167', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '拓殖大卒、ミサワホーム東京株式会社、株式会社プロジュクト・エフ（不動産/医療コンサル）、株式会社オーケスタ（医療コンサル）、株式会社アヤカト（医療コンサル）、株式会社エイエヌサポート（医療コンサル）', 42, null, '神田 督彦', 'status03'),
  ('applicant168', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '成蹊大卒、中小企業事業団、朝日監査法人（AA）、日立キャピタル、公益財団法人ライフ・エクステンション研究所、株式会社テイクアンドギヴ・ニーズ、\n 日商簿記検定2級 / その他（税理士科目合格、USCPA科目合格）', 43, null, '高島 れいや', 'status03'),
  ('applicant169', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '早稲田卒、三井住友海上\n TOEIC795\n アクチュアリー', 40, null, '岡田 里江子', 'status01'),
  ('applicant170', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、ソニー（通商部）\n TOEIC860', 38, null, '大城 友恵', 'status03'),
  ('applicant171', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東工大卒、ソニー（調査/分析/海外ラボ）\n TOEIC850', 43, null, '出口 荘介', 'status03'),
  ('applicant172', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、EYアドバイザリー（インダストリーヘッド）', 42, null, '茂木 敬', 'status03'),
  ('applicant173', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '京大卒、三井住友銀行、秋田県信用保証協会、株式会社日本ＭＡソリューション\n 日商簿記検定2級 / 中小企業診断士 / 証券アナリスト / 証券外務員一種 / 証券外務員二種 / その他（生命保険窓口販売 証券外務員内部管理責任者）', 52, null, '庄司 希', 'status03'),
  ('applicant174', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '中央大卒、株式会社日本アドシステム、岡田企画設立、株式会社ジェムコ日本経営', 43, null, '安井 孝彦', 'status03'),
  ('applicant175', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア（小売りセクターパートナー）', 53, null, '西田 是則', 'status01'),
  ('applicant176', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニー、Goldratt Consulting Ltd.（プリンシパル）\n TOEIC790', 51, null, '岸 房実', 'status03'),
  ('applicant177', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'BCG、マック（パートナー）', 37, null, '坂口 愛次郎', 'status03'),
  ('applicant178', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '中国国家公務員、新日本鉱油(株)、昭和アルミニウム株式会社、日中文化交流株式会社', 51, null, '山村 治行', 'status03'),
  ('applicant179', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '姫野さんのご紹介', null, null, '小泉 正征', 'status03'),
  ('applicant180', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ミネベア、オークローンマーケティング（情シス）', 49, null, '野崎 一馬', 'status03'),
  ('applicant181', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社浩栄インターナショナル、株式会社K・インターナショナル、株式会社オンズコンフィアンス、ステラグリーン株式会社\n （農業関連ビジネスに長く従事）', 39, null, '村井 有紀子', 'status03'),
  ('applicant182', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '有限会社月木レーシング レーシングメカニック、株式会社スキルズ（SE）、株式会社ジャック・インベストメント（M&Aアドバイザリー/経営管理）', 39, null, '前川 通', 'status03'),
  ('applicant183', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Citi（法人/個人営業、債券、プロジェクトファイナンス、デリバティブ等）', 39, null, '石井 鋭充', 'status03'),
  ('applicant184', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ハーバード卒、通産省、帝国ホテル、大阪ガス、医療財団法人慈誠会・野村病院（ 財団本部 部長）\n TOEIC990\n MBA', 46, null, '小島 克明', 'status03'),
  ('applicant185', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Boozリーガルコンサルタント', null, null, '大森 浩一郎', 'status03'),
  ('applicant186', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Boozリーガルコンサルタント', null, null, '石井 正次', 'status03'),
  ('applicant187', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '福岡工業大学卒、東大大学院MOT卒、東芝、ベイカレント、個人事業主\n TOEIC600（短期留学経験あり）', 39, null, '秋山 茂也', 'status03'),
  ('applicant188', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '畠山 広明', 'status03'),
  ('applicant189', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SCSK', 48, null, '木下 庸司', 'status03'),
  ('applicant190', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '中小の会計事務所を歴任\n 税理士、日商簿記検定1級、ファイナンシャル・プランナー（AFP/CFP）', 43, null, '藤沢 喜重', 'status03'),
  ('applicant191', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '国内大手証券会社、国際物流企業、外資系海運企業（CEO）\n MBA / 証券外務員一種 / 証券外務員二種 / その他（航空貨物取扱士）\n TOEIC960', 41, null, '宮下 十四夫', 'status03'),
  ('applicant192', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Producer Office CITY WAVE、株式会社サイズ入社（東京、LA,NY,Honolulu,Sydney,LONDONを拠点とする総合広告コーディネート会社）、株式会社デルフィス（旧南北社：トヨタ自動車１００％株保有 マーケティング会社）', 53, null, '宮下 勇美', 'status03'),
  ('applicant193', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱レイヨン、メリルリンチ証券、Thomson Financial Japan、エディンバラ・ファイナンシャル・パブリシング、Telekurs Financial Japan、Mysis International Banking Systems、RogueWave Software Japan、株式会社フジオー産業\n \n 証券アナリスト / 証券外務員一種 / 証券外務員二種\n TOEIC750', 55, null, '吉田 清重', 'status03'),
  ('applicant194', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '電通', 44, null, '佐伯 玲一', 'status03'),
  ('applicant195', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '山之内製薬、ノーベルファーマ', 56, null, '榎本 省次郎', 'status03'),
  ('applicant196', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日商岩井株式会社、モルガンスタンレー証券会社、株式会社エム・ファクトリー、フットワークインターナショナル株式会社、日本ビーオーシー株式会社(現、独Lindeグループ)、カナダ、ブリティッシュ・コロンビア州政府日本代表事務所', 49, null, '松尾 祐美', 'status03'),
  ('applicant197', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'シンガポール国立大学卒、BuildNow Pte Ltd、Nissin Kogyo, Co (Japan) 日伸工業株式会社、Nissin Kogyo (S) Pte Ltd & Straits Precision Ptd Ltd (now merged as NKS since 2009, and company name changed to Nissin Kogyou Asia Pte Ltd in Feb 2012)', 45, null, '長谷川 忠和', 'status03'),
  ('applicant198', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、株式会社オリエンタルランド\n TOEIC820', 31, null, '角田 亜依', 'status01'),
  ('applicant199', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トヨタ自動車株式会社、リーマンブラザーズ(アジアHQ) 、（株）ライクアート、トヨタ自動車株式会社、メットライフ?\n 英語上級', 40, null, '遠藤 僧三郎', 'status03'),
  ('applicant200', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '英国国立ケント大学卒、株式会社 ケイ・ウノ（ジュエリー製造販売）、東芝ITサービス株式会社（参議院会館常駐）、株式会社 シマダジュエリー', 31, null, '中野 耕介', 'status01'),
  ('applicant201', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '理想科学工業株式会社', 31, null, '篠崎 康司', 'status01'),
  ('applicant202', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、電通', 44, null, '秋田 裕紀', 'status03'),
  ('applicant203', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '国立国楽院、株式会社SOW（アセットマネジメント）、株式会社購買戦略研究所（BPOコンサルティングサービス）', 39, null, '山村 理恵子', 'status03'),
  ('applicant204', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '岡藤商事株式会社、ジェイビーシーサプライ株式会社（現在 C&Cビジネスサービス株式会社）\n TOEIC760', 43, null, '田辺 三起', 'status03'),
  ('applicant205', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶応卒、医療法人鉄蕉会亀田総合病院（経企/財務）、新日本有限責任監査法人、YIT Inc.(Hawaii, USA)インターン、学校法人順天堂（財務部）\n \n TOEIC880\n CPA（米国公認会計士） / CIA（公認内部監査人）', 31, null, '藤岡 信人', 'status03'),
  ('applicant206', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社サンドリーム（ECサイト運営等）、0&Company（Webコンサルティング）', 33, null, '谷川 希美', 'status03'),
  ('applicant207', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '住友不動産販売株式会社、トヨタファイナンス株式会社、株式会社豊田自動織機、ライトマネジメント株式会社、Tradesmen Enterprises Limited Partnership, カナダ アルバータ州（HRマネジメント）\n \n Agnew H. Johnston Public School, Thunder Bay（ファンドレイザー）、子供地球基金（東京）、\n \n カルガリー大学、カナダ アルバータ州カルガリー\n 人事管理サティフィケート（オンライン）', 42, null, '塚本 久作', 'status01'),
  ('applicant208', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NEC、デロイト香港', 31, null, '石橋 顕子', 'status01'),
  ('applicant209', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士ゼロックス株式会社（契約社員）、\n 富士通コンポーネント株式会社／トムソンロイタープロフェッショナル株式会社／株式会社三菱化学テクノリサーチ（業務委託）\n ピーロート・ジャパン株式会社（正社員）\n \n TOEIC860\n 情報活用試験１級合格\n DELE SUPERIOR取得（スペイン語上級）\n TOEIC公開テストスコア860\n 弁理士論文式試験合格', 40, null, '植田 亜衣', 'status03'),
  ('applicant210', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京農業大学卒、東京海上、日本コンサルタントシステム株式会社、SFPダイニング株式会社（旧サムカワフードプランニング株式会社）、新興エステート', 44, null, '松本 麻樹', 'status03'),
  ('applicant211', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本生命、電通、SKIJAPAN、慶應義塾大学SFC研究所\n \n 日商簿記検定2級 / MBA\n TOEIC805', 47, null, '大木 斎', 'status03'),
  ('applicant212', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本石油株式会社（現JXホールディング）、日本総研、株式会社アイピービー、IBCS、ビジネスアーキテクト（戦略ファーム）', 54, null, '福永 厚史', 'status03'),
  ('applicant213', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '帝京大学卒、大手SIer、投資関連企業他、アクアードコンサルティング', 31, null, '杉原 史男', 'status03'),
  ('applicant214', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソフトバンク・テクノロジー株式会社、SAMSUNG JAPAN CORPORATION、AIGエジソン、新光証券株式会社（現みずほ証券株式会社）、みなとアセットマネジメント株式会社、三菱東京UFJ銀行\n 証券外務員一種 / 証券外務員二種\n TOEIC740、韓国語/中国語', 36, null, '柴田 一城', 'status03'),
  ('applicant215', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'デーテックス オメダ株式会社 ※GEヘルスケアジャパン株式会社に吸収、日本オラクル株式会社、ソフトバンク テレコム株式会社', 39, null, '志村 公紀', 'status03'),
  ('applicant216', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ホテルフジタ、リレコジャパン株式会社、株式会社高橋商事、株式会社小学館集英社プロダクション、式会社インターシティ', 43, null, '内海 忠博', 'status03'),
  ('applicant217', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EY?\n ライズ（ベイカレ系）からオファー受領済みの若手の方', 27, null, '荒井 鉄次', 'status02'),
  ('applicant218', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'オックスフォード卒、EYA', 23, null, '笠原 麗奈', 'status01'),
  ('applicant219', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SIer、個人事業主（NEC傘下でホンダPJに数年アサイン中）\n \n 実力あるスーパーエンジニア', 31, null, '中尾 訓', 'status03'),
  ('applicant220', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '楽天（ECコンサルタント、事業開発/企画）', 31, null, '庄司 美次', 'status03'),
  ('applicant221', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '楽天', 29, null, '矢島 房男', 'status01'),
  ('applicant222', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'リーマン、楽天', null, null, '松原 秋徳', 'status03'),
  ('applicant223', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社アドヴィックス（自動車ブレーキのエンジニア）', 32, null, '白川 麗奈', 'status03'),
  ('applicant224', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ投信投資顧問株式会社、J&W Walker Farms、Japan Agricultural Exchange Council\n \n \n 日商簿記検定1級 / 証券アナリスト / 証券外務員二種\n TOEIC905\n フィリピン在住', 29, null, '田辺 悠里', 'status01'),
  ('applicant225', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ソフトクリエイト、サイボウズ、日本セーフネット株式会社\n \n 英語中級', 37, null, '岩崎 松代', 'status03'),
  ('applicant226', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '長谷工アーベスト、(株)住宅ネット、(株)ベイカレント・コンサルティング、(株)日立コンサルティング', 37, null, '宮城 絢子', 'status03'),
  ('applicant227', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソシエテ・ジェネラル証券株式会社（電算情報部）、株式会社オーシャンブリッジ\n \n 英国カーディフ大学ビジネススクール\n TOEIC950', 35, null, '工藤 新太郎', 'status03'),
  ('applicant228', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'マイルストーンターンアラウンドマネジメント株式会社', 27, null, '坂田 れいや', 'status01'),
  ('applicant229', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '(株)リクルートマーケティングパートナーズ\n \n TOEIC905', 26, null, '長谷川 和好', 'status01'),
  ('applicant230', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'コスコ・コンテナラインズジャパン、株式会社サイバー・コミュニケーションズ、ジンコーポレーション株式会社、株式会社ビジョン\n \n 広告領域\n 文京学院大学/経営学研究科（MBA）', 38, null, '手塚 靖雄', 'status03'),
  ('applicant231', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'フューチャーアーキテクト株式会社、エーシーキャピタル株式会社、株式会社社楽、株式会社明光ネットワークジャパン\n \n 新規事業、事業企画', 40, null, '大山 亜衣', 'status01'),
  ('applicant232', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '在ガーナ共和国日本国大使館、日本国際問題研究所、ユニバーサルミュージック、フロージャパン、ケリングジャパン（旧グッチグループジャパン）\n \n 財務/経理\n CPA（米国公認会計士） / MBA\n TOEIC850', 39, null, '須田 茂義', 'status03'),
  ('applicant233', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NEC、ACN小売/流通M（BD）', null, null, '岸本 美樹', 'status01'),
  ('applicant234', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN小売/流通SM', null, null, '齋藤 百里子', 'status01'),
  ('applicant235', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '西友（宣伝企画）、株式会社博報堂エルグ、スターフライヤー、株式会社ドリームホールディングス', 49, null, '宮内 和久', 'status03'),
  ('applicant236', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '米国カリフォルニア大学サンタクルーズ校、金融（投資研究・アナリスト・エコノミスト）\n \n 証券外務員資格（１種/２種）\n TOEIC960', 51, null, '八木 章一', 'status03'),
  ('applicant237', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'セバック株式会社（総務/人事/経理）、友部軌道工業株式会社（営業/工程企画）、久保税務会計事務所（株式会社ビジネスサービス）\n \n 日商簿記検定1級\n 税理士科目合格', 44, null, '清水 令', 'status03'),
  ('applicant238', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社アステル関西、インフォコム株式会社、株式会社ディー ツー コミュニケーションズ(現D2C) 、株式会社スプラッシュ設立 、株式会社HAMASHO', 41, null, '相馬 久紀', 'status03'),
  ('applicant239', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社キャズテック（海外電子部品のインバウンド営業、マーケティング）、株式会社アクロディア（海外市場ビジネス開発）、株式会社エムティーアイ（新規事業推進、中国ビジネス、ネット関連ビジネス）\n \n 英語ネイティブ', 45, null, '工藤 幸人', 'status03'),
  ('applicant240', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ニッセイ情報テクノロジー株式会社、 国際協力機構 青年海外協力隊（ヨルダン王国）、アビーム、KPMGコンサルティング株式会社 金融セクター マネージャー', 36, null, '大場 好博', 'status03'),
  ('applicant241', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '伊藤忠商事株式会社 宇宙・情報・マルチメディアカンパニー、伊藤忠インターナショナル(米国・ニューヨーク駐在)、マガシーク株式会社、伊藤忠オートモービル株式会社、エクソンモービル・ジャパン合同会社、株式会社カヤック\n \n TOEIC950', 38, null, '入江 常一', 'status03'),
  ('applicant242', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Cranfield University School of Management卒、エーオンジャパン株式会社\n \n TOEIC820', 40, null, '牧野 一馬', 'status03'),
  ('applicant243', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '伊勢丹、スポーツバンガード、STONES、ジーエスビー、個人事業主（中小企業の商品企画を通してのカイゼン）', 46, null, '山岡 平作', 'status03'),
  ('applicant244', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACNデジタル（元ストラテジー）', 36, null, '今野 有香', 'status01'),
  ('applicant245', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACNマネジャー', 33, null, '石川 孝彦', 'status03'),
  ('applicant246', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '本田さんお知り合い', 35, null, '工藤 兼典', 'status03'),
  ('applicant247', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 30, null, '大木 真紀子', 'status03'),
  ('applicant248', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 37, null, '榊原 千琴', 'status03'),
  ('applicant249', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 41, null, '西野 源三郎', 'status03'),
  ('applicant250', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 29, null, '小山 定二', 'status01'),
  ('applicant251', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'スシロー', 30, null, '金城 美里', 'status01'),
  ('applicant252', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SMBC日興証券', 28, null, '桑原 友', 'status01'),
  ('applicant253', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トムスク国立教育大学（翻訳、国際関係コンサルティング）', 32, null, '岡村 梨華', 'status03'),
  ('applicant254', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ｸﾞﾙｰﾎﾟﾝジャパン（人事）\n \n 英語上級', 44, null, '山根 梨華', 'status03'),
  ('applicant255', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'りそな銀行、東京コンサルティング、能率協会、ヘイ、KC（SM）\n \n HR領域（タレントマネジメント他）\n \n 南カリフォルニア大学経営学修士\n TOEIC900', 42, null, '山川 季雄', 'status01'),
  ('applicant256', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '堯昇實業股份有限公司(Taiwan Versa）、山梨県庁、ＪＴＢコーポレートセールス\n \n 英語上級', 32, null, '溝口 美海', 'status01'),
  ('applicant257', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京センチュリーリース、アデコ、株式会社ワークスソリューションズ、NTTデータ先端技術株式会社\n \n FP3級取得\n TOEIC865', 35, null, '須藤 孝成', 'status01'),
  ('applicant258', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア、国連開発計画(UNDP) 貧困削減ユニットインターン（サモア）、Symbiotics （インパクト投資ファンド)インターン（スイス）、国連貿易開発会議(UNCTAD) アフリカ・後発開発途上国部門インターン（スイス）、国際協力機構(JICA) アフリカ部アフリカ第二課、国連工業開発機関(UNIDO) アグリビジネス開発部（ウィーン）\n \n TOEIC980', 32, null, '片山 郁美', 'status03'),
  ('applicant259', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '新日鉄ソリューションズ株式会社、タカタ株式会社、株式会社エムティーアイ、株式会社サンエー・インターナショナル、株式会社エムティーアイ\n \n 日商簿記検定2級 / MBA\n TOEIC795', 39, null, '竹田 照和', 'status03'),
  ('applicant260', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'DHLサプライチェーン、株式会社フレクストロニクス、サーモフィッシャーサイエンティフック株式会社、エス・ピー・エス アンブラコ、エヌビディア合同会社\n \n Financeマネジャー/コントローラー\n \n 英検１級、英検準１級、TOEIC８９５点', 57, null, '伊藤 昌光', 'status03'),
  ('applicant261', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社 黒川雅之建築設計事務所、アトリエジャンヌーベル＋株式会社大林組、明治大学理工学部建築学科非常勤講師、愛知学院大学大学院経営学研究科非常勤講師\n \n トヨタ生産方式を基本とした生産現場の改革革新\n 中間管理職を対象としたマネジメントコンサルテーション\n ブランディング', 47, null, '新谷 淳子', 'status03'),
  ('applicant262', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ジャスネットコミュニケーションズ株式会社、阿久津健二税理士事務所、東京器工株式会社\n \n 日商簿記検定1級', 39, null, '山崎 友恵', 'status03'),
  ('applicant263', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '外務省 中南米カリブ課 専門調査員 在トリニダード・トバゴ日本国大使館 経済班\n \n 公認会計士資格取得の勉強中（2013年～）\n 国連英検Ａ級\n 第一種教員免許（中学校 英語・国語）（高等学校 英語）\n TOEIC850', 42, null, '金城 達太郎', 'status03'),
  ('applicant264', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '豊田通商(株)\n \n 財務部外国為替グループ\n 住環境部（東京） OEMビジネス営業\n 機械部（豊田） 工場資材供給ビジネス\n 工場資材供給ビジネス戦略室\n 顧客大手自動車メーカーT社調達（出向）\n 生産部品物流アウトソース受託ビジネス本部企画で戦略立案担当\n \n TOEIC735', 37, null, '西野 厚史', 'status01'),
  ('applicant265', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社メディシンク（委託）、株式会社光通信、みずほ証券、ドイツ証券、株式会社エアーエンターテイメント（社長室）、menue株式会社、現職（不明）\n \n 証券外務員二種 / その他（情報処理技術者試験 ITパスポート）\n 英語中級（恐らくビジネスレベル）', 39, null, '高松 尭道', 'status03'),
  ('applicant266', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '大和総研、PwC、AB\n \n パブリックセクターのヘルスケアチーム', 31, null, '松原 晃義', 'status03'),
  ('applicant267', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井物産（経企）、レイヤーズ、ベイカレント、EYA（SCM系）', 37, null, '阿部 正次', 'status01'),
  ('applicant268', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'タツミ商店、ミロク情報サービス、コスモ・イーシー、エスジーエス、DHLサプライチェーン株式会社、AQロジスティクス株式会社、エコ配', 48, null, '伊東 達生', 'status03'),
  ('applicant269', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '国交省、ACN', 28, null, '石崎 信弥', 'status03'),
  ('applicant270', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＤＹＮＡＳＴＹ ＪＡＰＡＮ 株式会社\n \n 英語上級', 31, null, '坂本 幸村', 'status03'),
  ('applicant271', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東芝、NTTCOM、オラクル、クオリカ（ITホールディングス）、キヤノンＩＴソリューションズ', 55, null, '村松 十三男', 'status03'),
  ('applicant272', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士通、東京コンサルティング\n \n 時短勤務中', 33, null, '志村 一人', 'status03'),
  ('applicant273', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'JAL、デルタ、 みずほコーポレート銀行 シンガポール支店\n \n MBA\n 英語ビジネスレベル', 42, null, '溝口 知実', 'status03'),
  ('applicant274', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本経済新聞社、 クレディ・スイス証券、TOKYO企業情報株式会社（M&Aアドバイザリー）\n \n 日本証券アナリスト協会検定会員\n 米国証券アナリスト（ＣＦＡ）レベル3受験生（2014年6月）\n TOEIC960', 38, null, '斎藤 健之', 'status03'),
  ('applicant275', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニーグローバルソリューションズ株式会社（経企）\n \n 2年間UKに在住（旦那さんに帯同）', 35, null, '宮本 亀男', 'status03'),
  ('applicant276', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'The Wharton School (MBA)卒\n オリックス、アジアネットK.K、e－エントリー、アスクル、富士ゼロックス（ビジネスイノーベーションシニアマネジャー | マーケティングスペシャリスト）\n \n 英語上級', 44, null, '大崎 越子', 'status01'),
  ('applicant277', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '長谷工コーポレーション、NYU留学、スタンダードアンドプアーズ、ソニー株式会社（コーポレート財務戦略）、JPモルガンチェースアンドカンパニー（バイス・プレジデント グローバル・デット・サービス 取引審査部）、NYU SternのTRIUM Global MBAに留学、住信基礎研究所、シービー・リチャードエリス（チーフコンサルタント）、東急不動産株式会社（海外事業部）、株式会社エジソンパワー（IPO準備）\n \n MBA / 証券外務員一種 / 証券外務員二種 / 宅地建物取引主任者\n 英語上級', 51, null, '土井 泰央', 'status03'),
  ('applicant278', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '梅田 由水', 'status03'),
  ('applicant279', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '西山 織枝', 'status01'),
  ('applicant280', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN', 27, null, '吉原 直紀', 'status01'),
  ('applicant281', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '鹿屋中央高等学校（教師）\n \n TOEIC865', 31, null, '田辺 友美', 'status01'),
  ('applicant282', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＨＩＳベトナム', 28, null, '小倉 房男', 'status01'),
  ('applicant283', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN\n \n TOEIC820', 33, null, '柏木 ナツ子', 'status03'),
  ('applicant284', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '丸山 道貴', 'status03'),
  ('applicant285', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '山根 真由美', 'status01'),
  ('applicant286', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＡＣＮ', null, null, '岩本 ひとみ', 'status01'),
  ('applicant287', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＡＣＮ', 37, null, '大城 陽一郎', 'status03'),
  ('applicant288', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '保険会社?、アビーム?、デロイト、KC、EY、ガートナー（シニアMD）', null, null, '東 益已', 'status03'),
  ('applicant289', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＡＣＮ、ＥＹＡ', null, null, '前田 有', 'status01'),
  ('applicant290', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA、Genpact', null, null, '川口 武俊', 'status03'),
  ('applicant291', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ベイカレント、ERA、ライズ、独立', null, null, '岡崎 桂', 'status03'),
  ('applicant292', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '監査法人トーマツ（名古屋）', 28, null, '坂井 れいや', 'status03'),
  ('applicant293', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '一橋卒、AIU（契約社員）', 29, null, '坂口 兼一', 'status03'),
  ('applicant294', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'BI関連の個人コンサル', 46, null, '中尾 三保子', 'status03'),
  ('applicant295', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '保険業界の経験が１３年間あり、管理職経験もある（株式会社損害保険ジャパン・ 株式会社東海日動パートナーズ）', 36, null, '横井 長一郎', 'status03'),
  ('applicant296', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'プルデンシャル生命保険（石川県）で働いていましたが、今離職中の状況です。', 35, null, '東 尚子', 'status03'),
  ('applicant297', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'JSR（価格メーカー）の10年間・物流やSCM企画部', 34, null, '中尾 多栄子', 'status03'),
  ('applicant298', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Intralink (ビジネス開発・コンサル）の若手社員。クリーンエネルギーのコンサルティングに転職する希望。', null, null, '松野 絵梨', 'status03'),
  ('applicant299', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'あいおいニッセイ同和損害保険株式会社', 31, null, '荒井 光保', 'status03'),
  ('applicant300', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'IT業界のマーケティングマネージャ(tekERP, Xcom Global, エーアイコーポレーション)', 39, null, '河合 秋美', 'status03'),
  ('applicant301', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（M）', null, null, '藤川 聖誉', 'status03'),
  ('applicant302', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（SM）', null, null, '荒木 博男', 'status03'),
  ('applicant303', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（M）', null, null, '須藤 勝夫', 'status03'),
  ('applicant304', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（M）', null, null, '後藤 虎之助', 'status01'),
  ('applicant305', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA', null, null, '小野寺 雄樹', 'status03'),
  ('applicant306', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA', null, null, '西 道貴', 'status03'),
  ('applicant307', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱長崎機工株式会社', 32, null, '菅原 久志', 'status03'),
  ('applicant308', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '津田工業株式会社', 46, null, '坂井 良市', 'status03'),
  ('applicant309', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ＡＣＮ', 29, null, '大沢 征輝', 'status03'),
  ('applicant310', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '大槻 真人', 'status03'),
  ('applicant311', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN（SM）', 39, null, '冨田 直秋', 'status03'),
  ('applicant312', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '立教大学、株式会社読売IS（法人営業）\n \n 日商簿記検定2級 / 中小企業診断士', 32, null, '宇野 久紀', 'status03'),
  ('applicant313', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日生（支払＋佐賀支社）5年、デロイト（FS：C）', 31, null, '加納 清重', 'status03'),
  ('applicant314', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN（リスクチーム）', null, null, '竹村 凱次', 'status03'),
  ('applicant315', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN（リスクチーム、M）', null, null, '畠山 鉄次', 'status01'),
  ('applicant316', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（SM）', null, null, '小西 明博', 'status03'),
  ('applicant317', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（SC)', null, null, '瀬戸 貴浩', 'status01'),
  ('applicant318', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（C)', null, null, '永田 直広', 'status01'),
  ('applicant319', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'シンプレクス（5年）、ACN（CM）', 29, null, '角田 定行', 'status01'),
  ('applicant320', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日生、デロイト', null, null, '浜野 市雄', 'status01'),
  ('applicant321', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN（CFM）', null, null, '井上 悠里', 'status03'),
  ('applicant322', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '岡三証券（富裕層向け営業）、専業主婦', null, null, '中西 泰美', 'status01'),
  ('applicant323', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EY・Ｇｏｌｄｍａｎ Sachs・Pasona HK', null, null, '坂井 絵美', 'status03'),
  ('applicant324', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'イグニションポイント株式会社・株式会社ノジマ', null, null, '関 則重', 'status03'),
  ('applicant325', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HK University, Toyota, Coca Cola', null, null, '浅田 伸江', 'status03'),
  ('applicant326', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Intralink, ECC', null, null, '山内 真希', 'status03'),
  ('applicant327', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA', null, null, '田上 明日香', 'status01'),
  ('applicant328', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'マニュライフ生命保険株式会社（FP）', 44, null, '和田 ひとみ', 'status03'),
  ('applicant329', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'University of OxfordMBA、大和市役所', 43, null, '今村 嘉彦', 'status01'),
  ('applicant330', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '学習院、第一生命、ソニーライフエイゴン生命、PGF生命（営業企画）', 44, null, '早川 智勝', 'status01'),
  ('applicant331', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（Cons）', 33, null, '藤野 譲介', 'status01'),
  ('applicant332', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（Cons）', null, null, '今村 茂平', 'status01'),
  ('applicant333', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（SC)', null, null, '吉田 清重', 'status03'),
  ('applicant334', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '商社（寺下さんご紹介）', null, null, '松崎 友子', 'status01'),
  ('applicant335', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'University of Wisconsin-Madison卒、日本MS、MS中国、ETC Shanghai, inc.', 43, null, '野沢 清重', 'status03'),
  ('applicant336', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社加寿翁コーポレーション、メットライフ生命保険株式会社', 30, null, '木村 葉子', 'status03'),
  ('applicant337', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN、IBM、デロイト（FS：ディレクター）', 46, null, '池田 信', 'status03'),
  ('applicant338', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Nuskin', 43, null, '谷口 富良', 'status03'),
  ('applicant339', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'En-World', null, null, '大谷 友隆', 'status03'),
  ('applicant340', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HP', null, null, '黒木 軍市', 'status03'),
  ('applicant341', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'メディア・ＷＥＢの事業本部長', 41, null, '小谷 鋭充', 'status03'),
  ('applicant342', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Ｓｏｎｙ', null, null, '西本 房実', 'status03'),
  ('applicant343', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SE・会計の資格', 35, null, '堀内 茂平', 'status03'),
  ('applicant344', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Global IT', null, null, '根岸 洵子', 'status03'),
  ('applicant345', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Global IT', null, null, '本間 昌昭', 'status03'),
  ('applicant346', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Marketing', null, null, '萩原 鉄次', 'status03'),
  ('applicant347', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Global IT', 36, null, '三好 光保', 'status01'),
  ('applicant348', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '中川 文典', 'status03'),
  ('applicant349', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '事業企画', null, null, '西尾 道彦', 'status03'),
  ('applicant350', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '海外営業', 34, null, '小原 隆吉', 'status03'),
  ('applicant351', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'IT・Coca Cola', 35, null, '森川 初', 'status03'),
  ('applicant352', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HR @ Yodogawa HU-Tech', 26, null, '川野 晴仁', 'status03'),
  ('applicant353', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Digital River APAC Recruiting Head', 33, null, '伊藤 克明', 'status03'),
  ('applicant354', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Pwc税理士法人', 31, null, '加藤 菊子', 'status03'),
  ('applicant355', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社プラスアルファ・コンサルティング', 33, null, '小谷 泰秀', 'status03'),
  ('applicant356', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '個人自営業者 （元科学メーカー・工場立ち上げの人事）', 45, null, '入江 克', 'status03'),
  ('applicant357', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '英会話学校', 30, null, '浜口 克', 'status03'),
  ('applicant358', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 34, null, '樋口 清重', 'status03'),
  ('applicant359', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NEC', 32, null, '竹下 梨枝子', 'status03'),
  ('applicant360', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '尚伯（北京）人力資源顧問有限公司', 34, null, '細川 火呂絵', 'status03'),
  ('applicant361', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HIS, Emirates', 33, null, '田辺 雄樹', 'status03'),
  ('applicant362', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社トキオゲッツ(広告会社)', 36, null, '志村 康伸', 'status03'),
  ('applicant363', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社AtmarkGroup', 33, null, '塚田 歩', 'status03'),
  ('applicant364', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Deloitte Tohmatsu 監査法人', 28, null, '丹羽 一馬', 'status03'),
  ('applicant365', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社アジアンパワー （自分の会社）', 42, null, '神谷 知実', 'status03'),
  ('applicant366', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社レナウン', 39, null, '松本 隆哉', 'status03'),
  ('applicant367', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社プシュケコンサルティング', 42, null, '大平 伸二', 'status01'),
  ('applicant368', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社マーベラスAQL', 40, null, '大谷 宗市', 'status03'),
  ('applicant369', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Accenture', 32, null, '新田 裕康', 'status03'),
  ('applicant370', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Toshiba 経営企画', 32, null, '新田 善英', 'status03'),
  ('applicant371', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '元Accenture, Credit Agricole', null, null, '渡辺 保行', 'status03'),
  ('applicant372', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東大、ボスコン（離職中）', 30, null, '小松 勤', 'status01'),
  ('applicant373', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Sier、大洋情報テクノロジー、EYA（SAPチーム：SC)', 38, null, '中原 義郎', 'status01'),
  ('applicant374', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（SAPチーム：M)', null, null, '藤原 美緒', 'status01'),
  ('applicant375', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA（ITA：M)', 40, null, '新田 茜', 'status01'),
  ('applicant376', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本旅行、アムウェイ（R&D製品開発マネジャー）、日本エア・リキード（仏企業、食品製薬R&D）、日本色材工業研究所（化粧品ODM/OEM）', 52, null, '福田 泰央', 'status01'),
  ('applicant377', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '伯東株式会社（電子デバイス営業）、Sojitz Asia Pte. Ltd. . Singapore（化学品原料の販売）', 34, null, '植田 真人', 'status01'),
  ('applicant378', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '自衛隊、警備会社、大阪ガス カスタマーリレーションズ株式会社（料金部門）', 39, null, '相沢 嘉邦', 'status01'),
  ('applicant379', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ビジネスコンサルタント、リブコンサルティング', 33, null, '菊池 要之助', 'status01'),
  ('applicant380', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '多賀志、サンクス、モードケース（美容師）', 36, null, '久保田 征二郎', 'status01'),
  ('applicant381', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ミサワホーム（営業）、野村ハイメディア株式会社（営業）、NTTコムマーケティング株式会社（国際電話サービスの法人営業）', 36, null, '平田 正進', 'status01'),
  ('applicant382', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ルネサンス（店舗Mgr）、株式会社エン・ジン（保育施設立上げ）、学校法人仁川学院（新規営利事業企画・運営）', 38, null, '川村 弘人', 'status01'),
  ('applicant383', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'パナソニックESシステムソフトウェア株式会社 / アプリケーションデザイン事業部', 32, null, '三木 平作', 'status01'),
  ('applicant384', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Sushi Train Smithfield（Aus）', 33, null, '手塚 功児', 'status01'),
  ('applicant385', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本生命（課長）', 32, null, '深沢 俊郎', 'status01'),
  ('applicant386', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '慶應義塾大学 / 環境情報学部（建設・都市分野・環境における調査員・リサーチャー）', 37, null, '宮崎 純隆', 'status01'),
  ('applicant387', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '帝人（商品開発、CSR）', 44, null, '林 裕紀', 'status01'),
  ('applicant388', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'テルモ、有限会社カタダ合成樹脂、日本GEプラスチック、BASFジャパン、サーモフィシャーサイエンティフィック', 49, null, '片桐 要子', 'status01'),
  ('applicant389', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本電信電話株式会社（NTT）及びNTTコミュニケーションズ株式会社（海外投資案件対応）、エス・エイチ・ツウ有限会社、豪州 クィーンズランド州環境省、JICA（マレーシア コタキナバル湿地センター）、株式会社バイリンガ（サイエンス顧問、カリキュラム作成）', 42, null, '竹中 真琴', 'status01'),
  ('applicant390', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'フィールズ株式会社 (コンテンツ事業の事業責任者）', 42, null, '川原 直秋', 'status03'),
  ('applicant391', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '楽天USAの事業担当役員', 41, null, '杉田 覚', 'status01'),
  ('applicant392', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'CE損害保険（株） 戦略企画統括本部 ゼネラルマネジャー', 51, null, '甲斐 梨枝子', 'status03'),
  ('applicant393', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Forum Engineering (エンジニア派遣業のマーケティング）', 27, null, '河野 宏季', 'status01'),
  ('applicant394', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '菱電機インフォメーションネットワーク株式会社', 29, null, '萩原 道和', 'status03'),
  ('applicant395', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社東芝 生産技術センター日本横浜\n グローバルモノづくり変革推進部', 29, null, '泉 れいな', 'status03'),
  ('applicant396', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '法政大学、楽天生命(情シス）', 32, null, '出口 貢太郎', 'status01'),
  ('applicant397', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN（M）', null, null, '後藤 広明', 'status01'),
  ('applicant398', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日立システムズ', 26, null, '島崎 三佐男', 'status03'),
  ('applicant399', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社アジェール (SE)', 33, null, '高田 礼子', 'status03'),
  ('applicant400', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'シンポー情報システム株式会社(SE)', 35, null, '筒井 広重', 'status03'),
  ('applicant401', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NTT Data Inc. （SE)', 35, null, '岡崎 徳彦', 'status02'),
  ('applicant402', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '無職 Back office業務のプロジェクトを希望', 40, null, '山本 武久', 'status03'),
  ('applicant403', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '投資銀行・USCPA, CMA, CFE, 証券外務員1種', 34, null, '神田 基', 'status03'),
  ('applicant404', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Softbank Marketing', 36, null, '田辺 友', 'status03'),
  ('applicant405', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'French Embassy Marketing', 26, null, '今村 慎吾', 'status01'),
  ('applicant406', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '関西インフライトケイタリング', 22, null, '大城 哲哉', 'status01'),
  ('applicant407', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '春秋航空', 39, null, '柏木 茂俊', 'status01'),
  ('applicant408', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ランドソリューション', 39, null, '荒川 良弥', 'status01'),
  ('applicant409', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'XEED、ラクスル', 28, null, '成田 兵吉', 'status01'),
  ('applicant410', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日生、SMBC日興証券 / 投資銀行部門', 34, null, '高野 秋代', 'status01'),
  ('applicant411', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '新日本有限責任監査法人（戦略マーケッツ事業部 パブリックアフェアーズ部）、BCG', 28, null, '青木 聡美', 'status01'),
  ('applicant412', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '(株)ダイヤモンドソサエティ 、N・フィールド、リベルテ、（株）ドロキア・オラシイタ', 41, null, '宇野 泰央', 'status01'),
  ('applicant413', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EY・PwCなどのコンサル経験', 40, null, '倉田 初', 'status01'),
  ('applicant414', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '翻訳者・グローバル環境が求めている', 29, null, '田上 保行', 'status03'),
  ('applicant415', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '中小企業の人事（人事制度の構築など）', 31, null, '大城 友子', 'status03'),
  ('applicant416', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'KMPG・Protivitのコンサル経験', 36, null, '石井 力弥', 'status03'),
  ('applicant417', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Accenture・Adidasの人事経験', 44, null, '小松 祥三', 'status03'),
  ('applicant418', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'DHLのBD（海外拠点での新規ビジネス開発）', 42, null, '吉沢 恵志', 'status03'),
  ('applicant419', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'BCG・外資系消費財のマーケティング（Unilever Japanなど）', 51, null, '川野 朋', 'status03'),
  ('applicant420', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '大学生', 22, null, '稲田 従典', 'status03'),
  ('applicant421', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Marketing background in chemicals and materials industry', 50, null, '谷川 鋭充', 'status03'),
  ('applicant422', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '法人営業（5年・繊維メーカー）と法律事務所の秘書', 34, null, '角田 尭道', 'status03'),
  ('applicant423', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'JR西日本', 33, null, '柳沢 要之助', 'status01'),
  ('applicant424', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Canon IT Solutions', 37, null, '神田 伝三郎', 'status03'),
  ('applicant425', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トーマツ（会計士）', 41, null, '石田 喜男', 'status01'),
  ('applicant426', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '新日本有限責任監査法人、オーストラリアニュージーランド銀行 東京支店、ニッセイアセットマネジメント株式会社、株式会社モルトベーネ', 41, null, '森川 智', 'status01'),
  ('applicant427', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ニュースキンジャパン株式会社、トーマツ', 39, null, '川野 平作', 'status01'),
  ('applicant428', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本信号（財務・経理、大阪在住）', 36, null, '谷 波子', 'status01'),
  ('applicant429', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '旅行関連企業、プラスチックシート・フィルム表面処理加工 及び製造の事務', 37, null, '吉村 文典', 'status01'),
  ('applicant430', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Webブランディング事業会社、マーケティング戦略立案事業会社、大手ゲーム・エンターテイメント会社（セガゲームズ）', 32, null, '飯島 玲', 'status01'),
  ('applicant431', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社カクタスコミュニケーションズ、株式会社MothersonSumi INfotech& Designs', 30, null, '栗田 直幸', 'status01'),
  ('applicant432', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社タチエス / 事業推進部海外事業管理課', 45, null, '中島 敏江', 'status03'),
  ('applicant433', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ECS / システム事業部', null, null, '川本 武久', 'status03'),
  ('applicant434', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '（株）国際開発センター', null, null, '関根 家継', 'status01'),
  ('applicant435', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '(株)野村総合研究所', null, null, '梅田 拓夫', 'status03'),
  ('applicant436', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '征路国際病院の事務', null, null, '古田 寿美', 'status01'),
  ('applicant437', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SAPの導入コンサルタント', null, null, '大沢 酉蔵', 'status03'),
  ('applicant438', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ベンチャーの保険会社の営業代理店の社長', null, null, '三木 俊郎', 'status03'),
  ('applicant439', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ネットウェイ / システム開発部', 35, null, '篠原 好和', 'status03'),
  ('applicant440', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '無職・元大学の講師（化学）、MIT卒', 36, null, '出口 武士', 'status03'),
  ('applicant441', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本精工（人事、営業）', 32, null, '須田 恵', 'status01'),
  ('applicant442', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井生命（営業）、エックスネット（金融機関向けシステム構築）、ウィーズ（調剤薬局社内SE）', 41, null, '多田 重三郎', 'status01'),
  ('applicant443', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '帝国ホテル、あらた', 36, null, '津田 偉生', 'status01'),
  ('applicant444', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'バンクーバー・イングリッシュ・センター、トヨタ自動車株式会社、トヨタメディアサービス（ＩＴ系、事業開発系）、テンプスタッフ・テクノロジー株式会社、グットマン（ニプログループ）', 42, null, '高野 和久', 'status01'),
  ('applicant445', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Mainet System株式会社（上海）、ANS株式会社（日本）、キャセイ．トライティク株式会社（日本）、 NeusoftJapan株式会社(日本)', 37, null, '大村 信也', 'status01'),
  ('applicant446', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱化成、日商岩井、ニフティ事業立上げ、衛星ビジネス展開、システム開発、ミャンマーなどでのビジネス展開', 52, null, '上原 敏継', 'status01'),
  ('applicant447', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士通(株) コンシューマトランザクション事業本部トータリゼータ事業部技術部、 (株)ネクスト21、(株)SIJテクノロジ 開発営業部マネージャー', 38, null, '角田 恒之', 'status01'),
  ('applicant448', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '横河・ヒューレット・パッカード（株）、アジレント・テクノロジー（株）、アジレント・テクノロジー・インターナショナル（株）、フランケコーヒーシステムズジャパン（株）、コグノス（株）、日本アイ・ビー・エム（株）', 54, null, '沼田 義勝', 'status01'),
  ('applicant449', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '多摩信金、岡三証券、EYA', 38, null, '馬場 郁穂', 'status01'),
  ('applicant450', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'サントリー、ベンチャー、EYA', 27, null, '岸 由文', 'status01'),
  ('applicant451', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA(Mgr)', 38, null, '奥野 香世子', 'status01'),
  ('applicant452', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア', null, null, '杉田 直子', 'status01'),
  ('applicant453', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '台湾勤務', 48, null, '若林 麗奈', 'status01'),
  ('applicant454', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日立、ビジョンコンサルティング', 29, null, '秋田 康次', 'status01'),
  ('applicant455', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井不動産レジデンシャル株式会社', 30, null, '大森 千代枝', 'status01'),
  ('applicant456', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア（ATS）、ベンチャー1年半、EYA（3年）', 38, null, '加納 隆吉', 'status01'),
  ('applicant457', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Sierを2社くらい？、EMS、EYA\n年齢: 38？', null, null, '比嘉 勝弘', 'status01'),
  ('applicant458', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ銀行', 42, null, '内海 志奈', 'status01'),
  ('applicant459', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ファイナンス、経企、M&A経験', 43, null, '内藤 公紀', 'status01'),
  ('applicant460', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ラオックス（転職6回以上）', 47, null, '山中 武久', 'status01'),
  ('applicant461', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア（転職6回以上）', 42, null, '河合 正宣', 'status01'),
  ('applicant462', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トムソン・ロイター・マーケッツ株式会社、ジャパンタイムズ、他', 39, null, '田村 基', 'status01'),
  ('applicant463', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'グローバルパートナーズ株式会社 / ドバイ営業部', 36, null, '宮本 都義', 'status03'),
  ('applicant464', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Eli lilly他（経企、M&A）\n \n CPAホルダー', 36, null, '菅 章緒', 'status01'),
  ('applicant465', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱東京UFJ銀行、みずほ銀行、野村証券、新生銀行', 43, null, '大崎 功児', 'status01'),
  ('applicant466', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア', 28, null, '村田 勝許', 'status01'),
  ('applicant467', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ミスミ', 45, null, '高島 則重', 'status01'),
  ('applicant468', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'インド総領事館、外務省、大学、ＪＩＣＡ', 39, null, '竹田 十四夫', 'status01'),
  ('applicant469', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN、アビーム、KC', 33, null, '長島 悠里', 'status01'),
  ('applicant470', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'コロンビア大、東大（環境系）', 40, null, '吉沢 敏継', 'status01'),
  ('applicant471', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '光通信、メタルワン、ベンチャー支援、飲食コンサル', 48, null, '小倉 千治', 'status01'),
  ('applicant472', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱UFJ銀行、おうちのクリニック', 30, null, '町田 知恵', 'status01'),
  ('applicant473', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本ストライカー、バイオメットジャパン、スタージャパン', 42, null, '川野 裕史', 'status01'),
  ('applicant474', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '医薬品メーカー（マーケティング）他', 48, null, '筒井 治行', 'status01'),
  ('applicant475', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '商社、リサーチャー（複数社）他', 36, null, '筒井 英造', 'status01'),
  ('applicant476', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HOYA（ブランクス事業部第一技術部開発４課）', 40, null, '片桐 理佐', 'status01'),
  ('applicant477', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'デイモンワールドワイドジャパンインク、DTFA、プラザクリエイト', 30, null, '中尾 義子', 'status01'),
  ('applicant478', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 35, null, '上野 邦美', 'status01'),
  ('applicant479', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Pwc F&Aアソシエイト（US？）', 30, null, '山根 江美', 'status01'),
  ('applicant480', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '新光投信株式会社、日本格付研究所、三菱総研、マネックス・ハンブレクト株式会社、メリルリンチ日本証券株式会社、ソニーライフエイゴン', 40, null, '井上 勝信', 'status01'),
  ('applicant481', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 36, null, '岡本 とみ子', 'status01'),
  ('applicant482', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 27, null, '松尾 祐次郎', 'status01'),
  ('applicant483', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日の出製作所、株式会社きらり', 38, null, '杉田 美津江', 'status01'),
  ('applicant484', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'パナソニックESネットワークス株式会社、他1社', 37, null, '福原 正宣', 'status01'),
  ('applicant485', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士重工業、日本アイ・ビー・エム、スタンダード＆プアーズ、メリルリンチ証券会社、ドイツ証券会社、ゴールドマンサックス証券会社、株式会社 ブレイブ、株式会社クレアン', 54, null, '田上 多紀子', 'status01'),
  ('applicant486', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA(Mgr)', 37, null, '林田 権一', 'status01'),
  ('applicant487', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社リクルート（現：株式会社リクルートライフスタイル）、NITTSU TRANSPORT SERVICE （M） SDN．BHD．、株式会社 フォーラムエンジニアリング、Intelligence Asia Pte. Ltd', 30, null, '中谷 繁樹', 'status01'),
  ('applicant488', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SBIマネープラザ、オリコンＤサイエンス、オリコン他', 33, null, '川口 亮子', 'status01'),
  ('applicant489', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'JACCS、株式会社ヘッドウォータース（海外進出コンサルティング）', 32, null, '黒川 信平', 'status01'),
  ('applicant490', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アンドモア', 54, null, '榊原 聖誉', 'status03'),
  ('applicant491', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Sega America', 37, null, '長谷川 都義', 'status03'),
  ('applicant492', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Bank of America・Meryll Lynch 人事', 38, null, '西 裕仁', 'status03'),
  ('applicant493', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SMBC信託銀行 / 経営企画部', 35, null, '北村 督彦', 'status03'),
  ('applicant494', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ネクストウェア株式会社', 45, null, '大崎 俊彰', 'status03'),
  ('applicant495', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 36, null, '村瀬 みき', 'status01'),
  ('applicant496', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', 31, null, '古川 美伸', 'status01'),
  ('applicant497', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京スター銀行営業統括、他にもＩＴ系の経験もあるとのこと', 39, null, '沼田 咲子', 'status01'),
  ('applicant498', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '神戸製鋼（知財）、B社（内部監査室）、中小コンサルティング会社（営業も担当）', 36, null, '桑原 朋', 'status01'),
  ('applicant499', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Deloitte Tax（海外大学卒）', 35, null, '大田 厚哉', 'status01'),
  ('applicant500', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ベイカレント、ACN', 32, null, '浅井 哲子', 'status01'),
  ('applicant501', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Protiviti（リスク管理）\n \n スペインの大学院卒（Barcelona School of Management Ponpeu Favra UniversityMSc of International Business）', 27, null, '今井 理恵子', 'status01'),
  ('applicant502', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ACN', null, null, '川端 彰揮', 'status01'),
  ('applicant503', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井物産フィナンシャルマネジメント\n \n CPA論文試験科目合格済み\n USCPAホルダー', 30, null, '安部 ひびき', 'status01'),
  ('applicant504', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '人材派遣・紹介の立上げ経験者（代表取締役経験者）', 55, null, '高橋 光次', 'status01'),
  ('applicant505', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '複数上場準備を経験済み、現在は個人事業主', 39, null, '藤岡 愛', 'status01'),
  ('applicant506', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'いすゞ自動車（マーケティング）', 33, null, '田口 聡', 'status01'),
  ('applicant507', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ハーバード卒、投資銀行、ファイナンスを長く経験', 52, null, '浜田 克三', 'status01'),
  ('applicant508', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '光通信、株式会社レインズインターナショナル 人事部長代理、株式会社パイオン JASDAQ4799 管理副本部長、株式会社ｴﾌﾃｨｺﾐｭﾆｹｰｼｮﾝｽﾞ JASDAQ2763 社長室特別顧問、株市会社AO', 43, null, '遠藤 伸江', 'status01'),
  ('applicant509', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ADK (報告代理店・タイ出向）', null, null, '小野 宗市', 'status02'),
  ('applicant510', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日産自動車', null, null, '服部 暉一郎', 'status03'),
  ('applicant511', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SE (現在ＨＫ滞在）', null, null, '大野 眞美', 'status03'),
  ('applicant512', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SE (現在Ireland滞在）', null, null, '今井 運吉', 'status03'),
  ('applicant513', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '野村證券（公認会計士）', 39, null, '河合 亀男', 'status03'),
  ('applicant514', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EY (America)・公認会計士', 26, null, '北野 伸樹', 'status02'),
  ('applicant515', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社アタックス・ビジネス・コンサルティング (公認会計士）', 40, null, '西山 初美', 'status03'),
  ('applicant516', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'PwC（M&A、再生）', 40, null, '泉 俊憲', 'status01'),
  ('applicant517', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トーマツ（会計士、名古屋）', 22, null, '大崎 有香', 'status01'),
  ('applicant518', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'スタンレー電気、株式会社サムスン日本研究所', 39, null, '林 善英', 'status01'),
  ('applicant519', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日経：c200265033\n \n デロイトトーマツコンサルティング、他に海外駐在経験もあり', 30, null, '大内 寿彦', 'status01'),
  ('applicant520', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'クレスコ、ACN', 39, null, '佐野 絵美', 'status01'),
  ('applicant521', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ証券・USCPA', 47, null, '小森 顕太郎', 'status03'),
  ('applicant522', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Ladies Fashion業界においてPR・マーケティング', 43, null, '茂木 良弥', 'status03'),
  ('applicant523', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社プロスペクト、トムソンロイタ- 、株式会社グロ-レン、アカマイ・キャピタル、株式会社フォックスマ-ク \n \n M&A、金融、幅広いインダストリーコンサルタント（インバウンドコンサルティング含め）', 40, null, '大野 文吾', 'status01'),
  ('applicant524', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'コニカミノルタ・', 39, null, '福田 靖雄', 'status02'),
  ('applicant525', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Cyberagent', 26, null, '桑原 光保', 'status02'),
  ('applicant526', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Metlife・公認会計士', 28, null, '丹羽 朗夫', 'status02'),
  ('applicant527', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'リ•カレント株式会社 / 人材組織開発プロデュース部\n \n 海外駐在が前提（バンコク希望）', 29, null, '野沢 一世', 'status01'),
  ('applicant528', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社経営システム研究所、インテリジェンス テクノブレ-ン、株式会社トライブ、株式会社レナウン、個人事業主', 32, null, '豊田 成子', 'status01'),
  ('applicant529', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'TIS', 30, null, '三浦 君吉', 'status03'),
  ('applicant530', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井住友海上火災保険株式会社（三井住友海上プライマリー生命）、GEキャピタル', 27, null, '神谷 水泉', 'status01'),
  ('applicant531', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社フェニックス(マーケティング）', 45, null, '塚田 勇四郎', 'status03'),
  ('applicant532', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Citybank, Pennisula Hotel （PR・広報）', 42, null, '近藤 圭織', 'status03'),
  ('applicant533', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Twitter, Google (Communications, Government Relationsなど）', 56, null, '山口 周平', 'status03'),
  ('applicant534', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Delta (sales and marketing)', 50, null, '内海 秋美', 'status03'),
  ('applicant535', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '有限責任 あずさ監査法人 （公認会計士）', 33, null, '樋口 武俊', 'status02'),
  ('applicant536', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '有限責任監査法人トーマツのスタッフ（公認会計士） LB0000043148', 45, null, '篠田 千治', 'status02'),
  ('applicant537', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'HP、ディーゼルジャパン、オーケー化成株式会社、ビジョンコンサルティング', 31, null, '谷本 麗奈', 'status01'),
  ('applicant538', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ATAGO会計事務所', 38, null, '栗原 多佳司', 'status01'),
  ('applicant539', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Digital Marketing (株式会社ハーパーコリンズ、Dell, Dragon Air)', 47, null, '池田 澄', 'status03'),
  ('applicant540', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Sumitomo Mitsui Trust (Hong Kong) Ltd\n 、他', 43, null, '堀江 陽子', 'status01'),
  ('applicant541', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'PM for 新規事業Projects in Pasona', 37, null, '大橋 美津江', 'status02'),
  ('applicant542', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社シグマクシス(SIGMAXYZ Inc.)\n のStrategy Consultant', 34, null, '柳田 益已', 'status02'),
  ('applicant543', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'SE・ITコンサルのPM\n ＮＴＴコムエンジニアリング株式会社', 35, null, '菊地 慶介', 'status03'),
  ('applicant544', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '人材採用', 39, null, '菅野 安彦', 'status03'),
  ('applicant545', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Leisure/Hospitality professional\n  Far East Hospitality , Singapore / Area General Manager', 43, null, '平野 康次', 'status02'),
  ('applicant546', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井不動産レジデンシャル株式会社 (海外営業)', 39, null, '木村 厚哉', 'status03'),
  ('applicant547', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'PR/ピーロート・ジャパン', 36, null, '小野 浩一郎', 'status01'),
  ('applicant548', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Netherlands chamber of commerce', 39, null, '小泉 和茂', 'status02'),
  ('applicant549', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'International Sales, Executive Assistant\n (Toyota Distributor in Saudi Arabia)', 32, null, '斉藤 忠博', 'status01'),
  ('applicant550', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Marketing (entertainment/content)', 41, null, '上原 真里', 'status03'),
  ('applicant551', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '派遣background (English, Russian, Japanese \n bilingual)', 26, null, '金田 一人', 'status03'),
  ('applicant552', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Berlitz', 25, null, '大木 幸信', 'status03'),
  ('applicant553', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Intreperter, Translator in Russia', 22, null, '黒木 一生', 'status03'),
  ('applicant554', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '住宅メーカー営業、アクサ営業＠神戸', 36, null, '西山 順子', 'status01'),
  ('applicant555', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ビースタイル、ジェネックスパートナーズ（M&A)、アビーム', 35, null, '大塚 幸人', 'status01'),
  ('applicant556', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トーマツイノベーション', 50, null, '小泉 禎二', 'status01'),
  ('applicant557', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ネオキャリア / 財務経理部', 30, null, '笠原 真知子', 'status01'),
  ('applicant558', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ウィングソリューションズ（他2社）', 35, null, '村山 佐十郎', 'status01'),
  ('applicant559', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社商工組合中央金庫', 32, null, '横山 さやか', 'status01'),
  ('applicant560', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'GMOクリック証券株式会社、プラネックスホールディング株式会社、日産センチュリー証券、ロンナルフォレックス株式会社', 37, null, '堤 豊司', 'status01'),
  ('applicant561', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アビーム、ＳＦＧＣ、株式会社三貴（ファッション・アパレル）', 35, null, '太田 顕子', 'status01'),
  ('applicant562', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EDGE INTERNATIONAL （ＩＲ,元Fast Retailing）', 28, null, '武井 隆昭', 'status02'),
  ('applicant563', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社ウエストゲイト (営業企画）', 28, null, '河合 真由美', 'status02'),
  ('applicant564', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'GIC(元ＳＥ、海外進出支援コンサル会社の経営企画）', 29, null, '原口 節美', 'status02'),
  ('applicant565', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Samsung, Amazon (経営企画）', 42, null, '浅井 幸博', 'status02'),
  ('applicant566', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '戦略コンサルタント', 45, null, '松尾 志津恵', 'status03'),
  ('applicant567', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Orix (銀行・M&A・監査法人の経験）', 35, null, '山岡 多佳司', 'status02'),
  ('applicant568', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Uishare（デジマの経験豊富）', 35, null, '小原 成夫', 'status01'),
  ('applicant569', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱ＵＦＪ信託銀行', 36, null, '渋谷 絵梨', 'status01'),
  ('applicant570', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'METI、東急不動産株式会社 / 東急不動産アクティビア投信(株)出向', 36, null, '奥山 敬吉', 'status01'),
  ('applicant571', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'リサーチ会社、他1社', 30, null, '角田 咲子', 'status01'),
  ('applicant572', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三井住友信託銀行', 30, null, '松尾 理絵', 'status01'),
  ('applicant573', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日立物流（アメリカ滞在の経験も）', 26, null, '青山 知生', 'status02'),
  ('applicant574', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '商工中央金庫、NTTデータ経営研究所', 31, null, '浜崎 嘉郎', 'status01'),
  ('applicant575', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '社内ＳＥ（ヤマトシステムなど）', 34, null, '園田 智美', 'status02'),
  ('applicant576', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'システム開発SE (岡三情報システム株式会社)', 31, null, '石山 悠里', 'status02'),
  ('applicant577', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東京コンサルティンググループ', 23, null, '角田 友子', 'status01'),
  ('applicant578', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'スクーナー株式会社、三井物産、カーギルジャパン、個人事業主（福島ＰＪ）', 40, null, '横山 嘉彦', 'status01'),
  ('applicant579', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '楽天、ACN', 29, null, '森本 裕行', 'status01'),
  ('applicant580', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Erickson Japan (SE・通信やモバイル系の専門）', 32, null, '矢島 喜重', 'status02'),
  ('applicant581', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Pactra Consulting (前職MUFJ証券）', 25, null, '中村 博男', 'status02'),
  ('applicant582', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ニッセイ、デロイト', 37, null, '上田 育雄', 'status01'),
  ('applicant583', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アクセンチュア、みずほ証券', 41, null, '笠原 三光', 'status01'),
  ('applicant584', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'オプト', null, null, '小野寺 理江', 'status01'),
  ('applicant585', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EYA', 24, null, '手塚 祐次郎', 'status01'),
  ('applicant586', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'リトルソフトウェア（元Tohmatus Financial Advisory)', 27, null, '横山 道義', 'status02'),
  ('applicant587', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本再生可能エネルギー株式会社・公認会計士', 37, null, '横井 優子', 'status02'),
  ('applicant588', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Oracle', 39, null, '桜井 政広', 'status02'),
  ('applicant589', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'PM・アメリカンホーム医療損害保険株式会社', 34, null, '大西 達太郎', 'status02'),
  ('applicant590', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '興銀リース株式会社ＩＴ課長 （元オリックスリースHead of IT)', 45, null, '井上 喜久郎', 'status02'),
  ('applicant591', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本ヒューレットパッカード株式会社 (IT・インフラコンサル）', 33, null, '田口 暉一郎', 'status02'),
  ('applicant592', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'EY transaction advisory services', 41, null, '大沢 光保', 'status02'),
  ('applicant593', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ソニーマーケティング、IBCS、ネクステック、コカ・コーラ、有限会社メテオール（戦略コンサル？）', 47, null, '高野 英充', 'status01'),
  ('applicant594', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '伊藤園（マーケ）、タリ-ズコ-ヒ-ジャパン株式会社（マーケ）、ユニ・チャ-ム株式会社（商品企画・マーケ）', 39, null, '山根 澄夫', 'status01'),
  ('applicant595', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'イオンクレジットサービス株式会社（少額短期保険）経営企画課長', 40, null, '三木 敬正', 'status01'),
  ('applicant596', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '味の素（バイオマス燃料や排出削減政策の研究や環境教育活動を担当）、株式会社長大（新規事業開発として、水環境、農業、廃棄物処理分野といった複数分野を横断的に担当、新興国経験もあり）', 35, null, '柳沢 真佐文', 'status01'),
  ('applicant597', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '三菱重工業株式会社 ITS事業ユニット 料金機械設計、ボッシュ株式会社 センサコンポーネント開発部、EYA、株式会社ワイ・ディ・シィー（製品開発力強化プロジェクトほか）', 35, null, '川野 敏江', 'status01'),
  ('applicant598', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ローム（半導体設計）、コニカミノルタビジネステクノロジーズ株式会社（複写機開発、ＬＳＩ）、株式会社図研（LSI受託設計）、図研エルミック株式会社（組み込みハード・ミドル開発・販売）', 49, null, '岡野 友子', 'status01'),
  ('applicant599', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '富士フィルム（ディーリング）', 26, null, '大崎 雅宏', 'status01'),
  ('applicant600', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ上海', 25, null, '大崎 凱次', 'status02'),
  ('applicant601', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Bangladesh IT会社（今福井大学で修士）', 29, null, '永田 理恵', 'status01'),
  ('applicant602', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '東芝（次世代メモリストレージの設計）', 32, null, '米田 一人', 'status01'),
  ('applicant603', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Cargil (ＳＣＭ本部）', 29, null, '内山 茂也', 'status02'),
  ('applicant604', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トーマツ、北海道中小企業総合支援センター、I＆R総合会計事務所\n \n CPA', 33, null, '平野 織枝', 'status01'),
  ('applicant605', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社リクルートマーケティングパートナーズ', 31, null, '福原 佑治', 'status02'),
  ('applicant606', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Accenture', 35, null, '岩田 宜昭', 'status02'),
  ('applicant607', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '住友生命保険相互会社(販売促進・営業）', 35, null, '二宮 宏機', 'status02'),
  ('applicant608', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '個人自営業コンサル・元戦略コンサルファーム・野村證券など', 55, null, '尾崎 彩', 'status02'),
  ('applicant609', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '戦略コンサルタント・元Deloitte', 49, null, '土井 江美', 'status02'),
  ('applicant610', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '戦略コンサルタント', 52, null, '小谷 佳紀', 'status02'),
  ('applicant611', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '日本オラクル（テクニカルサポート）', 28, null, '塚田 美己', 'status01'),
  ('applicant612', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'KPMGコンサルティング株式会社', 36, null, '寺田 善二', 'status02'),
  ('applicant613', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'AccentureＦＳ', 35, null, '西沢 征二郎', 'status02'),
  ('applicant614', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アビームコンサルティング', 55, null, '西尾 惣之助', 'status02'),
  ('applicant615', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '伊藤忠テクノソリューションズ株式会社', 33, null, '坂口 喜久郎', 'status02'),
  ('applicant616', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '', null, null, '新田 雅美', 'status02'),
  ('applicant617', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'NTCインターナショナル株式会社（海外農業開発コンサルティング）', 32, null, '金沢 友幸', 'status01'),
  ('applicant618', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ジーにーというアドテク会社の本部長', 35, null, '小島 幸信', 'status01'),
  ('applicant619', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'アビームコンサルティング / 戦略事業ユニット', 35, null, '後藤 達太郎', 'status01'),
  ('applicant620', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '経営共創基盤・戦略コンサル', 35, null, '杉浦 和茂', 'status01'),
  ('applicant621', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ベイカレント・コンサルティング / コンサルティング&IT事業本部', 38, null, '金井 長一郎', 'status01'),
  ('applicant622', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'BDO Sanyu & Co. （監査法人）にてM&A\n TOEIC970', 32, null, '畑中 美波留', 'status01'),
  ('applicant623', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'デロイト', 42, null, '平野 成子', 'status01'),
  ('applicant624', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'みずほ銀行 / グローバルコーポレート業務部\n TOEIC825', 36, null, '横井 秀司', 'status01'),
  ('applicant625', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'デロイトトーマツファイナンシャルアドバイザリー', 41, null, '西村 睦男', 'status01'),
  ('applicant626', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '株式会社クレディア（営業、債権管理）、あずさ、日本住宅株式会社（内部監査、原価管理など）\n 公認会計士', 44, null, '本多 正次', 'status01'),
  ('applicant627', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'トランスコスモス株式会社（デジタルマーケティング）、株式会社トライフォート（経企として新規事業、マネジメントレポート、IPO準備）', 27, null, '神谷 禎二', 'status01'),
  ('applicant628', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'Willcom、フリーランス（営業派遣）、アジア系金融機関（財務分析）', 38, null, '長田 令', 'status01'),
  ('applicant629', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '学生時代に起業、トレイダーズ証券、株式会社ゴードン・ブラザーズ・ジャパン（動産処理）、アビーム（銀行・証券）、フェリスウィールインベストメント株式会社（投資から何まで、観覧車も）', 34, null, '北野 雅臣', 'status01'),
  ('applicant630', 'inaba', 'inaba', SYSDATE(), SYSDATE(), 'ウォルト・ディズニー・アニメーション・ジャパン株式会社、ディー・エイチ・エル・グローバルメール・ジャパン株式会社', 40, null, '渡部 準司', 'status01'),
  ('applicant631', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '静岡銀行', 36, null, '竹本 好行', 'status01'),
  ('applicant632', 'inaba', 'inaba', SYSDATE(), SYSDATE(), '電通、A.T.カー二ー、Globis Capital Partners、KPMG FAS、ACNストラテジー、シグマ、ドンキホーテ・ホールディングス', 40, null, '内海 奈緒美', 'status01');
