INSERT INTO statuses (id, domain, name, created_by, created_at, updated_by, updated_at) VALUES
  ('status01', 'applicant', '新規', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status02', 'applicant', '活動中', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status03', 'applicant', '活動停止', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status04', 'applicant', '削除', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status05', 'application', '準備中', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status06', 'application', '選考中', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status07', 'application', '内定', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status08', 'application', '入社', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status09', 'application', 'Close (求職側NG)', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status10', 'application', 'Close (求人側NG)', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status11', 'application', 'Close (その他)', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status12', 'task', 'Open', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status13', 'task', 'Done', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status14', 'task', 'Suspend', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status15', 'company', 'Open', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status16', 'company', 'Close', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status17', 'job', 'Open', 'inaba', SYSDATE(), 'inaba', SYSDATE()),
  ('status18', 'job', 'Close', 'inaba', SYSDATE(), 'inaba', SYSDATE());
