# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "um"
  config.vm.network :private_network, ip: "192.168.22.178"
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.synced_folder "./rw-um/", "/home/vagrant/rw-um", group: 'vagrant', owner: 'vagrant'
  config.vm.provision :shell, path: "./vagrant_provision.sh", privileged: false
end
