# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "front"
  config.vm.network :private_network, ip: "192.168.11.178"
  config.vm.provision :file, source: "./file/settings.xml", destination: "/home/vagrant/.m2/settings.xml"
  config.vm.provision :shell, path: "./vagrant_provision.sh", privileged: false
  config.vm.synced_folder "./rw-front", "/home/vagrant/rw-front", group: 'vagrant', owner: 'vagrant'
end
